// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 族 (zú)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" zú"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"z"}</_components.strong>{" like "}<_components.strong>{"\"z\""}</_components.strong>{" in \"zebra\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ú"}</_components.strong>{" sounds like "}<_components.strong>{"\"oo\""}</_components.strong>{" in \"zoo\" but with second tone → rising tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"zú"}</_components.strong>{" sounds like "}<_components.strong>{"\"zoo?\""}</_components.strong>{" with a questioning rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" (´) is a "}<_components.strong>{"rising"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're asking about someone's family background: "}<_components.strong>{"\"zú?\""}</_components.strong>{" — that rising tone suggests\ninquiry about kinship!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"族 (zú) - \"clan, ethnic group, family\""}</_components.li>{"\n"}<_components.li>{"民族 (mín zú) - \"ethnic group, nationality\""}</_components.li>{"\n"}<_components.li>{"家族 (jiā zú) - \"family clan\""}</_components.li>{"\n"}<_components.li>{"种族 (zhǒng zú) - \"race, ethnicity\""}</_components.li>{"\n"}<_components.li>{"族人 (zú rén) - \"clanspeople, ethnic group members\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"When asking about someone's "}<_components.strong>{"clan"}</_components.strong>{" or ethnic background, your voice naturally rises with curiosity\n— just like the rising second tone of "}<_components.strong>{"zú"}</_components.strong>{"!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Cultural Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"族 is important in Chinese culture and politics, especially in terms like 中华民族 (Chinese nation)\nand referring to China's 56 recognized ethnic groups."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
