// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 绿 (lǜ)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" lǜ"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"l"}</_components.strong>{" like "}<_components.strong>{"\"l\""}</_components.strong>{" in \"look\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǜ"}</_components.strong>{" sounds like "}<_components.strong>{"\"ü\""}</_components.strong>{" in German (or \"ue\" sound), but with fourth tone → sharp falling"}</_components.li>{"\n"}<_components.li><_components.strong>{"lǜ"}</_components.strong>{" sounds like "}<_components.strong>{"\"lyue!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Special Note on ǜ:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"ǜ"}</_components.strong>{" sound is made by:"}</_components.p>{"\n"}<_components.ol>{"\n"}<_components.li>{"Round your lips like saying \"oo\""}</_components.li>{"\n"}<_components.li>{"But position your tongue like saying \"ee\""}</_components.li>{"\n"}<_components.li>{"Then add the sharp falling fourth tone"}</_components.li>{"\n"}</_components.ol>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (`) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like pointing out something green: "}<_components.strong>{"\"lǜ!\""}</_components.strong>{" — start high and drop down."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"绿色 (lǜ sè) - \"green color\""}</_components.li>{"\n"}<_components.li>{"绿茶 (lǜ chá) - \"green tea\""}</_components.li>{"\n"}<_components.li>{"绿豆 (lǜ dòu) - \"mung bean\""}</_components.li>{"\n"}<_components.li>{"绿灯 (lǜ dēng) - \"green light\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of the vibrant "}<_components.strong>{"green"}</_components.strong>{" of nature — that bold, definitive color matches the sharp tone!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
