// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 卡 (kǎ)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" kǎ"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"k"}</_components.strong>{" like "}<_components.strong>{"\"k\""}</_components.strong>{" in \"cat\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǎ"}</_components.strong>{" sounds like "}<_components.strong>{"\"ah\""}</_components.strong>{" but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"kǎ"}</_components.strong>{" sounds like "}<_components.strong>{"\"kah\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone: Say it like you're thinking: "}<_components.strong>{"\"kǎ...\""}</_components.strong>{" —\nthat's the tone pattern."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"卡 (kǎ) - \"card\""}</_components.li>{"\n"}<_components.li>{"卡片 (kǎ piàn) - \"card\""}</_components.li>{"\n"}<_components.li>{"信用卡 (xìn yòng kǎ) - \"credit card\""}</_components.li>{"\n"}<_components.li>{"银行卡 (yín háng kǎ) - \"bank card\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"卡 can also be pronounced "}<_components.strong>{"kǎ"}</_components.strong>{" (third tone) meaning \"card\" or "}<_components.strong>{"qiǎ"}</_components.strong>{" (third tone) meaning \"stuck;\njammed\", but the card meaning with "}<_components.strong>{"kǎ"}</_components.strong>{" is most common."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
