// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 害 (hài)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" hài"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"h"}</_components.strong>{" like "}<_components.strong>{"\"h\""}</_components.strong>{" in \"hat\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ài"}</_components.strong>{" sounds like "}<_components.strong>{"\"eye\""}</_components.strong>{" but with fourth tone → sharp downward drop"}</_components.li>{"\n"}<_components.li><_components.strong>{"hài"}</_components.strong>{" sounds like "}<_components.strong>{"\"hi!\""}</_components.strong>{" with a sharp falling tone"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (ˋ) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like expressing alarm about danger: "}<_components.strong>{"\"hài!\""}</_components.strong>{" — that sharp drop conveys the seriousness of\n"}<_components.strong>{"harm"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"害 (hài) - \"to harm; injure; damage\""}</_components.li>{"\n"}<_components.li>{"害怕 (hài pà) - \"to be afraid; scared\""}</_components.li>{"\n"}<_components.li>{"害羞 (hài xiū) - \"to be shy; bashful\""}</_components.li>{"\n"}<_components.li>{"伤害 (shāng hài) - \"to hurt; harm\""}</_components.li>{"\n"}<_components.li>{"危害 (wēi hài) - \"to endanger; harm\""}</_components.li>{"\n"}<_components.li>{"厉害 (lì hai) - \"formidable; serious; severe\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"📍 Usage Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"害 can mean physical harm, emotional damage, or being afraid. The context determines the specific\nmeaning, but it generally relates to negative effects or fear."}</_components.p>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p><_components.strong>{"Injure"}</_components.strong>{" — the sharp falling fourth tone is like the sudden shock of getting "}<_components.strong>{"hurt"}</_components.strong>{"!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
