// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 加 (jiā)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" jiā"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note: "}<_components.strong>{"\"Jiaaa\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"j"}</_components.strong>{" like "}<_components.strong>{"\"j\""}</_components.strong>{" in \"jeep\" but softer, like \"gee\""}</_components.li>{"\n"}<_components.li><_components.strong>{"iā"}</_components.strong>{" sounds like "}<_components.strong>{"\"ya\""}</_components.strong>{" in \"yard\" but held steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"jiā"}</_components.strong>{" sounds like "}<_components.strong>{"\"jya\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like announcing something important: "}<_components.strong>{"\"jiā!\""}</_components.strong>{" — keep that high, steady tone."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"加 (jiā) - \"add\""}</_components.li>{"\n"}<_components.li>{"加油 (jiā yóu) - \"add fuel, come on!\" (encouragement)"}</_components.li>{"\n"}<_components.li>{"加工 (jiā gōng) - \"processing\""}</_components.li>{"\n"}<_components.li>{"加强 (jiā qiáng) - \"strengthen\""}</_components.li>{"\n"}<_components.li>{"加快 (jiā kuài) - \"speed up\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"jiā"}</_components.strong>{" as \"yeah!\" with enthusiasm — you're adding energy or excitement!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
