// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 创 (chuàng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" chuàng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"ch"}</_components.strong>{" like "}<_components.strong>{"\"ch\""}</_components.strong>{" in \"chair\""}</_components.li>{"\n"}<_components.li><_components.strong>{"uàng"}</_components.strong>{" sounds like "}<_components.strong>{"\"wahng\""}</_components.strong>{", but with fourth tone → sharp falling"}</_components.li>{"\n"}<_components.li><_components.strong>{"chuàng"}</_components.strong>{" sounds like "}<_components.strong>{"\"chwahng!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (`) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're making a decisive statement: "}<_components.strong>{"\"chuàng!\""}</_components.strong>{" — that's the tone pattern of\n"}<_components.strong>{"chuàng"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"创 (chuàng) - \"begin; create\""}</_components.li>{"\n"}<_components.li>{"创业 (chuàng yè) - \"start a business\""}</_components.li>{"\n"}<_components.li>{"创作 (chuàng zuò) - \"create; compose\""}</_components.li>{"\n"}<_components.li>{"创新 (chuàng xīn) - \"innovate\""}</_components.li>{"\n"}<_components.li>{"创造 (chuàng zào) - \"create; invent\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"创 means \"begin/create\" — imagine the decisive "}<_components.strong>{"falling"}</_components.strong>{" tone as the moment you "}<_components.strong>{"create"}</_components.strong>{"\nsomething new!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
