// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 咖 (kā)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" kā"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note: "}<_components.strong>{"\"Eeee\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"k"}</_components.strong>{" like "}<_components.strong>{"\"k\""}</_components.strong>{" in \"kite\", but with a strong aspiration"}</_components.li>{"\n"}<_components.li><_components.strong>{"ā"}</_components.strong>{" sounds like "}<_components.strong>{"\"ah\""}</_components.strong>{" in \"father\", but held steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"kā"}</_components.strong>{" sounds like "}<_components.strong>{"\"kah\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're holding a steady musical note: "}<_components.strong>{"\"kā...\""}</_components.strong>{" — keep the pitch high and level."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"咖 (kā) - \"coffee\" (used in compound words)"}</_components.li>{"\n"}<_components.li>{"咖啡 (kā fēi) - \"coffee\""}</_components.li>{"\n"}<_components.li>{"咖啡店 (kā fēi diàn) - \"coffee shop\""}</_components.li>{"\n"}<_components.li>{"咖啡馆 (kā fēi guǎn) - \"cafe\""}</_components.li>{"\n"}<_components.li>{"咖啡豆 (kā fēi dòu) - \"coffee beans\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Usage Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"咖 (kā) is "}<_components.strong>{"rarely used alone"}</_components.strong>{" — it's almost always part of the compound word 咖啡 (kā fēi)\nmeaning \"coffee\". The character itself doesn't have an independent meaning in modern Chinese."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
