// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 井 (jǐng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" jǐng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"j"}</_components.strong>{" like "}<_components.strong>{"\"j\""}</_components.strong>{" in \"jeep\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǐng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ing\""}</_components.strong>{" in \"sing\", but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"jǐng"}</_components.strong>{" sounds like "}<_components.strong>{"\"jing\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip (Third tone: ˇ)"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone, like looking down into something deep:"}</_components.p>{"\n"}<_components.p>{"Say it like you're peering thoughtfully into a deep well: "}<_components.strong>{"\"jǐng...\""}</_components.strong>{" — that contemplative\ndip-and-rise is the "}<_components.strong>{"third tone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"井 (jǐng) - \"well; water well\""}</_components.li>{"\n"}<_components.li>{"水井 (shuǐ jǐng) - \"water well\""}</_components.li>{"\n"}<_components.li>{"油井 (yóu jǐng) - \"oil well\""}</_components.li>{"\n"}<_components.li>{"井水 (jǐng shuǐ) - \"well water\""}</_components.li>{"\n"}<_components.li>{"深井 (shēn jǐng) - \"deep well\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"井"}</_components.strong>{" as looking down thoughtfully into a deep well — that's the "}<_components.strong>{"third tone"}</_components.strong>{"\ndownward-then-upward movement!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Visual Connection:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The character 井 actually looks like the grid pattern you might see when looking down into a\ntraditional well with wooden supports!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
