// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 思 (sī)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" sī"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"s"}</_components.strong>{" like "}<_components.strong>{"\"s\""}</_components.strong>{" in \"see\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ī"}</_components.strong>{" sounds like "}<_components.strong>{"\"ee\""}</_components.strong>{" in \"see\" but with first tone → steady high pitch"}</_components.li>{"\n"}<_components.li><_components.strong>{"sī"}</_components.strong>{" sounds like "}<_components.strong>{"\"see\""}</_components.strong>{" with a steady high tone"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (¯) is "}<_components.strong>{"high and flat"}</_components.strong>{":"}</_components.p>{"\n"}<_components.p>{"Say it like you're thinking steadily and clearly: "}<_components.strong>{"\"sī...\""}</_components.strong>{" — that steady, contemplative tone\nmatches the meaning of \"think.\""}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"思 (sī) - \"think; thought\""}</_components.li>{"\n"}<_components.li>{"思想 (sī xiǎng) - \"thought; thinking; ideology\""}</_components.li>{"\n"}<_components.li>{"思考 (sī kǎo) - \"think; ponder; reflect\""}</_components.li>{"\n"}<_components.li>{"意思 (yì si) - \"meaning; intention\""}</_components.li>{"\n"}<_components.li>{"思念 (sī niàn) - \"miss; long for\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"思 is often used in compound words related to thinking and mental processes. The steady first tone\ngives it a contemplative, intellectual quality."}</_components.p>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The steady, high first tone "}<_components.strong>{"sī"}</_components.strong>{" sounds like a long, thoughtful \"hmm...\" — perfect for the\ncharacter meaning \"think\"!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
