// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 推 (tuī)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" tuī"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"t"}</_components.strong>{" like "}<_components.strong>{"\"t\""}</_components.strong>{" in \"tea\" (but with a slight puff of air)"}</_components.li>{"\n"}<_components.li><_components.strong>{"uī"}</_components.strong>{" sounds like "}<_components.strong>{"\"way\""}</_components.strong>{", but held steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"tuī"}</_components.strong>{" sounds like "}<_components.strong>{"\"tway\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like singing a steady high note: "}<_components.strong>{"\"tuī~~~\""}</_components.strong>{" — that's the flat, steady tone of "}<_components.strong>{"tuī"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"推 (tuī) - \"push\""}</_components.li>{"\n"}<_components.li>{"推广 (tuī guǎng) - \"promote; popularize\""}</_components.li>{"\n"}<_components.li>{"推进 (tuī jìn) - \"advance; push forward\""}</_components.li>{"\n"}<_components.li>{"推迟 (tuī chí) - \"postpone; delay\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"\"推\""}</_components.strong>{" as "}<_components.strong>{"\"tway\""}</_components.strong>{" held steady — like steadily pushing something forward!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
