// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 哪 (nǎ)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" nǎ"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"n"}</_components.strong>{" like "}<_components.strong>{"\"n\""}</_components.strong>{" in \"no\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǎ"}</_components.strong>{" sounds like "}<_components.strong>{"\"ah\""}</_components.strong>{" in \"father\", but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"nǎ"}</_components.strong>{" sounds like "}<_components.strong>{"\"nah\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're questioning or wondering: "}<_components.strong>{"\"nǎ...\""}</_components.strong>{" — that questioning tone fits perfectly with\n\"which?\""}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"哪 (nǎ) - \"which\""}</_components.li>{"\n"}<_components.li>{"哪个 (nǎ ge) - \"which one\""}</_components.li>{"\n"}<_components.li>{"哪里 (nǎ lǐ) - \"where\""}</_components.li>{"\n"}<_components.li>{"哪儿 (nǎr) - \"where\" (Beijing dialect)"}</_components.li>{"\n"}<_components.li>{"哪些 (nǎ xiē) - \"which ones\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"mouth radical (口)"}</_components.strong>{" plus "}<_components.strong>{"那"}</_components.strong>{" — when you ask "}<_components.strong>{"\"which\""}</_components.strong>{" with your mouth, you're pointing\nand questioning, creating that rising-falling tone pattern!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
