// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 氐 (dī)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" dī"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note: "}<_components.strong>{"\"Dee\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"d"}</_components.strong>{" like "}<_components.strong>{"\"d\""}</_components.strong>{" in \"deep\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ī"}</_components.strong>{" sounds like "}<_components.strong>{"\"ee\""}</_components.strong>{" in \"see\" but held steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"dī"}</_components.strong>{" sounds like "}<_components.strong>{"\"dee\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip (First tone: ˉ)"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" is "}<_components.strong>{"high and flat"}</_components.strong>{", like holding a steady note:"}</_components.p>{"\n"}<_components.p>{"Say it like you're pointing to the bottom of something: "}<_components.strong>{"\"dī...\""}</_components.strong>{" — that steady, high tone is the\n"}<_components.strong>{"first tone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"氐 (dī) - \"bottom; base; foundation\""}</_components.li>{"\n"}<_components.li>{"Used mainly as a radical component in other characters"}</_components.li>{"\n"}<_components.li>{"Related to concepts of foundation or bottom"}</_components.li>{"\n"}<_components.li>{"Appears in characters like:"}{"\n"}<_components.ul>{"\n"}<_components.li>{"低 (dī) - \"low\""}</_components.li>{"\n"}<_components.li>{"底 (dǐ) - \"bottom\""}</_components.li>{"\n"}</_components.ul>{"\n"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"氐 is primarily used as a radical component in modern Chinese rather than as a standalone word. It\nconveys the meaning of \"bottom\" or \"foundation\" and appears in characters related to low positions\nor bases."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
