logFilters:
  # Force Yarn to error (exit non-zero) if peer dependencies aren't met
  # correctly.
  #
  # This was enabled after an issue where a peer dependency was silently
  # mismatched.
  #
  # > ➤ YN0060: │ @lottiefiles/dotlottie-react is listed by your project with
  # > version 0.12.3 (pf2a39), which doesn't satisfy what lottie-react-native
  # > requests (~0.6.5).
  #
  # This is easy to do accidentally and might be something Renovate accidentally
  # does too.
  - code: YN0060
    level: error
  - level: discard
    text: "@lottiefiles/dotlottie-react is listed by your project with version 0.13.5 (pea19c), which doesn't satisfy what lottie-react-native requests (~0.6.5)."

nmMode: hardlinks-local # Speed boost

nodeLinker: node-modules

npmMinimalAgeGate: 0

# Don't automatically run constraints checks after `yarn install`, because they
# could be a little slow and they're on the critical path. They're run
# separately in CI.
enableConstraintsChecks: false

packageExtensions:
  "@expo/cli@*":
    peerDependencies:
      expo-constants: "*"
      expo-font: "*"
      react: "*"
  "@react-email/components@0.x":
    peerDependencies:
      react-dom: "*"
  "@rn-primitives/dropdown-menu@1.x":
    peerDependencies:
      react-dom: "*"
  "@tanstack/react-db@0.x":
    peerDependencies:
      typescript: "*"
  babel-plugin-transform-flow-enums@0.x:
    peerDependencies:
      "@babel/core": "*"
  babel-preset-expo@57.x:
    peerDependencies:
      "@babel/core": "*"
  expo-auth-session@57.x:
    peerDependencies:
      expo: "*"
  expo-dev-client@57.x:
    peerDependencies:
      react-native: "*"
  expo-linking@57.x:
    peerDependencies:
      expo: "*"
  expo-router@57.x:
    peerDependencies:
      "@testing-library/dom": "*"
      expo-font: "*"
  expo@57.x:
    peerDependencies:
      "@babel/core": "*"
  inngest@4.x:
    peerDependencies:
      "@opentelemetry/core": "*"
  moti@0.x:
    peerDependencies:
      react: "*"
      react-dom: "*"
  recma-jsx@1.x:
    peerDependencies:
      acorn: "*"

yarnPath: .yarn/releases/yarn-4.18.1.cjs
