nodeLinker: node-modules
nmMode: hardlinks-local # Speed boost

yarnPath: .yarn/releases/yarn-4.14.1.cjs

logFilters:
  # Force Yarn to error (exit non-zero) if peer dependencies aren't met
  # correctly.
  #
  # This was enabled after an issue where a peer dependency was silently
  # mismatched.
  #
  # > ➤ YN0060: │ @lottiefiles/dotlottie-react is listed by your project with
  # > version 0.12.3 (pf2a39), which doesn't satisfy what lottie-react-native
  # > requests (~0.6.5).
  #
  # This is easy to do accidentally and might be something Renovate accidentally
  # does too.
  - code: YN0060
    level: error
  - text: "@lottiefiles/dotlottie-react is listed by your project with version 0.13.5 (pea19c), which doesn't satisfy what lottie-react-native requests (~0.6.5)."
    level: discard

packageExtensions:
  "moti@0.x":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "inngest@4.x":
    peerDependencies:
      "@opentelemetry/core": "*"
  "expo-router@57.x":
    peerDependencies:
      expo-font: "*"
      "@testing-library/dom": "*"
  "expo@57.x":
    peerDependencies:
      "@babel/core": "*"
  "expo-linking@57.x":
    peerDependencies:
      expo: "*"
  "expo-dev-client@57.x":
    peerDependencies:
      react-native: "*"
  "expo-auth-session@57.x":
    peerDependencies:
      expo: "*"
  "babel-plugin-transform-flow-enums@0.x":
    peerDependencies:
      "@babel/core": "*"
  "babel-preset-expo@57.x":
    peerDependencies:
      "@babel/core": "*"
  "@tanstack/react-db@0.x":
    peerDependencies:
      "typescript": "*"
  "@rn-primitives/dropdown-menu@1.x":
    peerDependencies:
      "react-dom": "*"
  "recma-jsx@1.x":
    peerDependencies:
      "acorn": "*"
  "@react-email/components@0.x":
    peerDependencies:
      "react-dom": "*"
  "@expo/cli@*":
    peerDependencies:
      "expo-constants": "*"
      "expo-font": "*"
      "react": "*"
