nodeLinker: node-modules
nmMode: hardlinks-local # Speed boost

yarnPath: .yarn/releases/yarn-4.9.2.cjs

logFilters:
  # Force Yarn to error (exit non-zero) if peer dependencies aren't met
  # correctly.
  #
  # This was enabled after an issue where a peer dependency was silently
  # mismatched.
  #
  # > ➤ YN0060: │ @lottiefiles/dotlottie-react is listed by your project with
  # > version 0.12.3 (pf2a39), which doesn't satisfy what lottie-react-native
  # > requests (~0.6.5).
  #
  # This is easy to do accidentally and might be something Renovate accidentally
  # does too.
  - code: YN0060
    level: error
  - text: "@lottiefiles/dotlottie-react is listed by your project with version 0.13.5 (pea19c), which doesn't satisfy what lottie-react-native requests (~0.6.5)."
    level: discard
