// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 候 (hòu)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" hòu"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"h"}</_components.strong>{" like "}<_components.strong>{"\"h\""}</_components.strong>{" in \"hat\""}</_components.li>{"\n"}<_components.li><_components.strong>{"òu"}</_components.strong>{" sounds like "}<_components.strong>{"\"oh\""}</_components.strong>{" in \"oh no\", but with fourth tone → sharp falling"}</_components.li>{"\n"}<_components.li><_components.strong>{"hòu"}</_components.strong>{" sounds like "}<_components.strong>{"\"hoh!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (`) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like giving a firm command: "}<_components.strong>{"\"hòu!\""}</_components.strong>{" — that's the tone pattern of "}<_components.strong>{"hòu"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"候 (hòu) - \"to wait; time; season\""}</_components.li>{"\n"}<_components.li>{"等候 (děng hòu) - \"to wait\""}</_components.li>{"\n"}<_components.li>{"时候 (shí hou) - \"time; moment\""}</_components.li>{"\n"}<_components.li>{"候选人 (hòu xuǎn rén) - \"candidate\""}</_components.li>{"\n"}<_components.li>{"气候 (qì hòu) - \"climate\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"📝 Special Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"In the common word 时候 (shí hou), the 候 is pronounced as a neutral tone "}<_components.strong>{"hou"}</_components.strong>{" (without tone\nmarking), not the fourth tone "}<_components.strong>{"hòu"}</_components.strong>{"."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
