// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 消 (xiāo)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" xiāo"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"x"}</_components.strong>{" like "}<_components.strong>{"\"sh\""}</_components.strong>{" in \"she\" (but softer, more like \"hs\")"}</_components.li>{"\n"}<_components.li><_components.strong>{"iāo"}</_components.strong>{" sounds like "}<_components.strong>{"\"yow\""}</_components.strong>{" in \"yowl\", but with first tone → high and steady"}</_components.li>{"\n"}<_components.li><_components.strong>{"xiāo"}</_components.strong>{" sounds like "}<_components.strong>{"\"shee-ow\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're holding a steady note: "}<_components.strong>{"\"xiāo\""}</_components.strong>{" — that's the tone pattern of "}<_components.strong>{"xiāo"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"消 (xiāo) - \"vanish/disappear\""}</_components.li>{"\n"}<_components.li>{"消息 (xiāo xi) - \"news/information\""}</_components.li>{"\n"}<_components.li>{"消费 (xiāo fèi) - \"consume/consumption\""}</_components.li>{"\n"}<_components.li>{"消失 (xiāo shī) - \"disappear/vanish\""}</_components.li>{"\n"}<_components.li>{"消化 (xiāo huà) - \"digest/digestion\""}</_components.li>{"\n"}<_components.li>{"取消 (qǔ xiāo) - \"cancel\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"消 (xiāo) contains the water radical (氵) on the left. Think of water evaporating and vanishing into\nthin air — just like how 消 means to vanish or disappear!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
