// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 图 (tú)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" tú"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question: "}<_components.strong>{"\"Really?\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"t"}</_components.strong>{" like "}<_components.strong>{"\"t\""}</_components.strong>{" in \"top\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ú"}</_components.strong>{" sounds like "}<_components.strong>{"\"oo\""}</_components.strong>{" in \"too\", but with second tone → rising pitch"}</_components.li>{"\n"}<_components.li><_components.strong>{"tú"}</_components.strong>{" sounds like "}<_components.strong>{"\"too?\""}</_components.strong>{" with a questioning rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" (ˊ) starts "}<_components.strong>{"low"}</_components.strong>{" and rises "}<_components.strong>{"up"}</_components.strong>{":"}</_components.p>{"\n"}<_components.p>{"Say it like you're asking about a picture: "}<_components.strong>{"\"tú?\""}</_components.strong>{" — that's the rising tone of "}<_components.strong>{"tú"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"图 (tú) - \"picture; image; diagram\""}</_components.li>{"\n"}<_components.li>{"图片 (tú piàn) - \"picture; image\""}</_components.li>{"\n"}<_components.li>{"图书馆 (tú shū guǎn) - \"library\""}</_components.li>{"\n"}<_components.li>{"地图 (dì tú) - \"map\""}</_components.li>{"\n"}<_components.li>{"意图 (yì tú) - \"intention; plan\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"图"}</_components.strong>{" (picture) like asking \"tú?\" — questioning what's in the image!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
