// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 头 (tóu)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" tóu"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"t"}</_components.strong>{" like "}<_components.strong>{"\"t\""}</_components.strong>{" in \"top\""}</_components.li>{"\n"}<_components.li><_components.strong>{"óu"}</_components.strong>{" sounds like "}<_components.strong>{"\"oh\""}</_components.strong>{", but with second tone → rising pitch"}</_components.li>{"\n"}<_components.li><_components.strong>{"tóu"}</_components.strong>{" sounds like "}<_components.strong>{"\"toe?\""}</_components.strong>{" with a questioning rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" (´) is a "}<_components.strong>{"rising"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're asking \"Really?\": "}<_components.strong>{"\"tóu?\""}</_components.strong>{" — that's the upward rise of the "}<_components.strong>{"second tone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"头 (tóu) - \"head\""}</_components.li>{"\n"}<_components.li>{"头发 (tóu fà) - \"hair\""}</_components.li>{"\n"}<_components.li>{"头痛 (tóu tòng) - \"headache\""}</_components.li>{"\n"}<_components.li>{"石头 (shí tóu) - \"stone\""}</_components.li>{"\n"}<_components.li>{"馒头 (mán tóu) - \"steamed bread\""}</_components.li>{"\n"}<_components.li>{"从头开始 (cóng tóu kāi shǐ) - \"start from the beginning\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"头 is a very common and versatile character in Chinese. It can mean \"head\" literally, but also\nappears in many compound words where it can mean \"beginning,\" \"top,\" or serve as a suffix for\nvarious objects (like 石头 for \"stone\")."}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Usage Patterns:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"As a body part: 头 (head)"}</_components.li>{"\n"}<_components.li>{"As a suffix: 石头 (stone), 木头 (wood)"}</_components.li>{"\n"}<_components.li>{"In expressions: 头一次 (first time), 头等 (first class)"}</_components.li>{"\n"}</_components.ul></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
