// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 旦 (dàn)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" dàn"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"d"}</_components.strong>{" like "}<_components.strong>{"\"d\""}</_components.strong>{" in \"dog\""}</_components.li>{"\n"}<_components.li><_components.strong>{"àn"}</_components.strong>{" sounds like "}<_components.strong>{"\"ahn\""}</_components.strong>{" in \"barn\" but with fourth tone → sharp falling tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"dàn"}</_components.strong>{" sounds like "}<_components.strong>{"\"dahn!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (`) is a sharp "}<_components.strong>{"falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're announcing the break of dawn: "}<_components.strong>{"\"dàn!\""}</_components.strong>{" — that decisive tone captures the\ndefinitive moment when day begins!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"旦 (dàn) - \"dawn, morning, day\""}</_components.li>{"\n"}<_components.li>{"元旦 (yuán dàn) - \"New Year's Day\""}</_components.li>{"\n"}<_components.li>{"一旦 (yī dàn) - \"once, as soon as\""}</_components.li>{"\n"}<_components.li>{"旦夕 (dàn xī) - \"morning and evening, short time\""}</_components.li>{"\n"}<_components.li>{"旦日 (dàn rì) - \"dawn, daybreak\" (literary)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p><_components.strong>{"Dawn"}</_components.strong>{" breaks decisively and suddenly — just like the sharp fourth tone of "}<_components.strong>{"dàn"}</_components.strong>{"!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Cultural Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"旦 combines the sun (日) with a horizontal line representing the horizon, visually depicting the sun\nrising at dawn. It's commonly seen in 元旦 (New Year's Day)."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
