// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 握 (wò)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" wò"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"w"}</_components.strong>{" like "}<_components.strong>{"\"w\""}</_components.strong>{" in \"way\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ò"}</_components.strong>{" sounds like "}<_components.strong>{"\"aw\""}</_components.strong>{" in \"awful\", but with fourth tone → sharp fall"}</_components.li>{"\n"}<_components.li><_components.strong>{"wò"}</_components.strong>{" sounds like "}<_components.strong>{"\"waw\""}</_components.strong>{" with a sharp downward drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (ˋ) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're firmly grasping something: "}<_components.strong>{"\"wò!\""}</_components.strong>{" — that's the decisive falling tone of\n"}<_components.strong>{"wò"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"握 (wò) - \"grasp; hold\""}</_components.li>{"\n"}<_components.li>{"握手 (wò shǒu) - \"shake hands\""}</_components.li>{"\n"}<_components.li>{"把握 (bǎ wò) - \"grasp; control\""}</_components.li>{"\n"}<_components.li>{"掌握 (zhǎng wò) - \"master; grasp\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"\"握\""}</_components.strong>{" as "}<_components.strong>{"\"waw\""}</_components.strong>{" with a sharp drop — like firmly grasping something in your hand!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
