// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 调 (tiáo)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" tiáo"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question: "}<_components.strong>{"\"Really?\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"t"}</_components.strong>{" like "}<_components.strong>{"\"t\""}</_components.strong>{" in \"tea\""}</_components.li>{"\n"}<_components.li><_components.strong>{"iáo"}</_components.strong>{" sounds like "}<_components.strong>{"\"ee-ow\""}</_components.strong>{" blended together with a rising tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"tiáo"}</_components.strong>{" sounds like "}<_components.strong>{"\"tee-ow?\""}</_components.strong>{" with a questioning rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip (Second tone: ˊ)"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" is "}<_components.strong>{"rising"}</_components.strong>{", like when you're adjusting something and checking:"}</_components.p>{"\n"}<_components.p>{"Say it like you're asking "}<_components.strong>{"\"Is this the right adjustment?\""}</_components.strong>{": "}<_components.strong>{"\"tiáo?\""}</_components.strong>{" — that upward tone is the\n"}<_components.strong>{"second tone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"调 (tiáo) - \"adjust; tune; regulate\""}</_components.li>{"\n"}<_components.li>{"调节 (tiáo jié) - \"adjust; regulate\""}</_components.li>{"\n"}<_components.li>{"调整 (tiáo zhěng) - \"adjust; readjust\""}</_components.li>{"\n"}<_components.li>{"调查 (tiáo chá) - \"investigate; survey\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Multiple Pronunciations:"}</_components.strong></_components.p>{"\n"}<_components.p>{"调 has different pronunciations for different meanings:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"tiáo"}</_components.strong>{" (2nd tone) - \"adjust; tune; investigate\""}</_components.li>{"\n"}<_components.li><_components.strong>{"diào"}</_components.strong>{" (4th tone) - \"tone; melody; key (in music)\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p>{"The pronunciation "}<_components.strong>{"tiáo"}</_components.strong>{" (second tone) is used when 调 means \"to adjust\" or \"to investigate\"."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
