// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 站 (zhàn)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" zhàn"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"zh"}</_components.strong>{" like "}<_components.strong>{"\"j\""}</_components.strong>{" in \"junk\" but with tongue curled back"}</_components.li>{"\n"}<_components.li><_components.strong>{"àn"}</_components.strong>{" sounds like "}<_components.strong>{"\"an\""}</_components.strong>{" in \"can\", but with fourth tone → sharp drop"}</_components.li>{"\n"}<_components.li><_components.strong>{"zhàn"}</_components.strong>{" sounds like "}<_components.strong>{"\"jahn!\""}</_components.strong>{" with a sharp falling command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (ˋ) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Start high and drop sharply: "}<_components.strong>{"\"zhàn!\""}</_components.strong>{" — like giving a firm command to stop and stand."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"站 (zhàn) - \"stand; station\""}</_components.li>{"\n"}<_components.li>{"站住 (zhàn zhù) - \"stop; halt\""}</_components.li>{"\n"}<_components.li>{"火车站 (huǒ chē zhàn) - \"train station\""}</_components.li>{"\n"}<_components.li>{"地铁站 (dì tiě zhàn) - \"subway station\""}</_components.li>{"\n"}<_components.li>{"网站 (wǎng zhàn) - \"website\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of commanding someone to "}<_components.strong>{"\"jahn!\""}</_components.strong>{" (stop and stand) — the sharp fourth tone matches the\nauthority of the command!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
