// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 犬 (quǎn)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" quǎn"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"q"}</_components.strong>{" like "}<_components.strong>{"\"ch\""}</_components.strong>{" in \"cheese\" but with lips rounded"}</_components.li>{"\n"}<_components.li><_components.strong>{"uǎn"}</_components.strong>{" sounds like "}<_components.strong>{"\"wahn\""}</_components.strong>{" but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"quǎn"}</_components.strong>{" sounds like "}<_components.strong>{"\"chwahn\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're thinking about a dog: "}<_components.strong>{"\"quǎn...\""}</_components.strong>{" — that thoughtful dip-and-rise is the "}<_components.strong>{"third\ntone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"犬 (quǎn) - \"dog\" (formal/literary)"}</_components.li>{"\n"}<_components.li>{"猎犬 (liè quǎn) - \"hunting dog\""}</_components.li>{"\n"}<_components.li>{"警犬 (jǐng quǎn) - \"police dog\""}</_components.li>{"\n"}<_components.li>{"牧羊犬 (mù yáng quǎn) - \"sheepdog\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"犬"}</_components.strong>{" as thoughtfully considering a dog: "}<_components.strong>{"\"quǎn...\""}</_components.strong>{" — that contemplative tone matches\nthe "}<_components.strong>{"third tone"}</_components.strong>{"!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Usage Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"犬 is a more formal/literary word for dog. In everyday speech, 狗 (gǒu) is more commonly used."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
