// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 睛 (jīng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" jīng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note: "}<_components.strong>{"\"Ahhhh\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"j"}</_components.strong>{" like "}<_components.strong>{"\"j\""}</_components.strong>{" in \"jeep\""}</_components.li>{"\n"}<_components.li><_components.strong>{"īng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ing\""}</_components.strong>{" in \"sing\" but held steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"jīng"}</_components.strong>{" sounds like "}<_components.strong>{"\"jing\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like stating clearly: "}<_components.strong>{"\"jīng—\""}</_components.strong>{" — that's the clear tone pattern of "}<_components.strong>{"jīng"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"睛 (jīng) - \"eyeball; pupil\""}</_components.li>{"\n"}<_components.li>{"眼睛 (yǎn jīng) - \"eyes\" (most common usage)"}</_components.li>{"\n"}<_components.li>{"火眼金睛 (huǒ yǎn jīn jīng) - \"eyes of fire and gold\" (sharp eyesight)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"\"jing\""}</_components.strong>{" with a steady, clear tone — the "}<_components.strong>{"eyeball"}</_components.strong>{" is the clear, focused part of the\neye that sees everything distinctly!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"睛 is rarely used alone and is most commonly seen in the compound 眼睛 (yǎn jīng) meaning \"eyes\"."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
