// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 品 (pǐn)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" pǐn"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"p"}</_components.strong>{" like "}<_components.strong>{"\"p\""}</_components.strong>{" in \"pin\" (unaspirated, softer than English \"p\")"}</_components.li>{"\n"}<_components.li><_components.strong>{"ǐn"}</_components.strong>{" sounds like "}<_components.strong>{"\"een\""}</_components.strong>{" in \"seen\", but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"pǐn"}</_components.strong>{" sounds like "}<_components.strong>{"\"peen\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're thoughtfully evaluating something: "}<_components.strong>{"\"pǐn...\""}</_components.strong>{" — that's the tone pattern of\n"}<_components.strong>{"pǐn"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"品 (pǐn) - \"product; goods\""}</_components.li>{"\n"}<_components.li>{"产品 (chǎn pǐn) - \"product\""}</_components.li>{"\n"}<_components.li>{"商品 (shāng pǐn) - \"commodity\""}</_components.li>{"\n"}<_components.li>{"用品 (yòng pǐn) - \"supplies\""}</_components.li>{"\n"}<_components.li>{"食品 (shí pǐn) - \"food products\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Remember the "}<_components.strong>{"three mouths (口)"}</_components.strong>{" in 品 — you need to taste with your mouth to judge the quality of\na "}<_components.strong>{"product"}</_components.strong>{"!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
