// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 乙 (yǐ)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" yǐ"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"y"}</_components.strong>{" like "}<_components.strong>{"\"y\""}</_components.strong>{" in \"yes\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǐ"}</_components.strong>{" sounds like "}<_components.strong>{"\"ee\""}</_components.strong>{" in \"see\" but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"yǐ"}</_components.strong>{" sounds like "}<_components.strong>{"\"yee\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it thoughtfully, like you're considering something — "}<_components.strong>{"\"yǐ...\""}</_components.strong>{" — that contemplative tone fits\nthe meaning of "}<_components.strong>{"\"second\""}</_components.strong>{" as in ranking."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"乙 (yǐ) - \"second (in order), B-grade\""}</_components.li>{"\n"}<_components.li>{"甲乙 (jiǎ yǐ) - \"A and B, first and second\""}</_components.li>{"\n"}<_components.li>{"乙级 (yǐ jí) - \"B-grade, second class\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"📍 Traditional Usage:"}</_components.strong></_components.p>{"\n"}<_components.p>{"乙 is the "}<_components.strong>{"second"}</_components.strong>{" of the ten traditional Chinese stems (甲乙丙丁...), often used for:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Grading"}</_components.strong>{": 乙级 (B-grade)"}</_components.li>{"\n"}<_components.li><_components.strong>{"Ordering"}</_components.strong>{": 甲方乙方 (Party A, Party B)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p><_components.strong>{"Second place"}</_components.strong>{" gets the thoughtful third tone — like you're pondering "}<_components.strong>{"\"Hmm, second...\""}</_components.strong></_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
