// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 常 (cháng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" cháng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"ch"}</_components.strong>{" like "}<_components.strong>{"\"ch\""}</_components.strong>{" in \"change\""}</_components.li>{"\n"}<_components.li><_components.strong>{"áng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ahng\""}</_components.strong>{" but with rising tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"cháng"}</_components.strong>{" sounds like "}<_components.strong>{"\"chahng\""}</_components.strong>{" with a questioning rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip (Second tone: ˊ)"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" is a "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question:"}</_components.p>{"\n"}<_components.p>{"Say it like asking \""}<_components.strong>{"often"}</_components.strong>{"?\": "}<_components.strong>{"\"cháng?\""}</_components.strong>{" — that rising, questioning tone is the "}<_components.strong>{"second\ntone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"常 (cháng) - \"often; frequently\""}</_components.li>{"\n"}<_components.li>{"常常 (cháng cháng) - \"often; frequently\""}</_components.li>{"\n"}<_components.li>{"非常 (fēi cháng) - \"very; extremely\""}</_components.li>{"\n"}<_components.li>{"正常 (zhèng cháng) - \"normal\""}</_components.li>{"\n"}<_components.li>{"日常 (rì cháng) - \"daily; everyday\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"常"}</_components.strong>{" as asking \""}<_components.strong>{"often"}</_components.strong>{"?\" with that rising, curious tone — that's the "}<_components.strong>{"second tone"}</_components.strong>{"\nquality!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
