// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 者 (zhě)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" zhě"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"hmm\" when thinking"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"zh"}</_components.strong>{" like "}<_components.strong>{"\"j\""}</_components.strong>{" in \"judge\" (but with tongue curled back)"}</_components.li>{"\n"}<_components.li><_components.strong>{"ě"}</_components.strong>{" sounds like "}<_components.strong>{"\"uh\""}</_components.strong>{" in \"duh\", but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"zhě"}</_components.strong>{" sounds like "}<_components.strong>{"\"juh\""}</_components.strong>{" with a contemplative dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're thoughtfully referring to someone: "}<_components.strong>{"\"zhě...\""}</_components.strong>{" — that's the reflective tone\npattern of "}<_components.strong>{"zhě"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"者 (zhě) - \"person, one who\" (suffix for people)"}</_components.li>{"\n"}<_components.li>{"记者 (jì zhě) - \"journalist, reporter\""}</_components.li>{"\n"}<_components.li>{"作者 (zuò zhě) - \"author, writer\""}</_components.li>{"\n"}<_components.li>{"读者 (dú zhě) - \"reader\""}</_components.li>{"\n"}<_components.li>{"学者 (xué zhě) - \"scholar\""}</_components.li>{"\n"}<_components.li>{"消费者 (xiāo fèi zhě) - \"consumer\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p><_components.strong>{"者"}</_components.strong>{" is often used as a suffix to describe \"a person who does something\" — use that thoughtful\nthird tone when identifying someone's role!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
