name: 📦 Metro cache
description: Enable metro caching for faster builds in CI.

runs:
  using: composite
  steps:
    - name: Find Metro cache
      id: metro-cache-dir-path
      uses: actions/github-script@v9
      with:
        result-encoding: string
        script: |
          const os = require('node:os');
          const path = require('node:path');
          return path.join(os.tmpdir(), 'metro-cache');

    - name: Restore Metro cache
      uses: actions/cache@v5
      with:
        path: ${{ steps.metro-cache-dir-path.outputs.result }}
        key: metro-cache-${{ runner.os }}-${{ hashFiles('yarn.lock', 'projects/app/metro.config.*') }}
