// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 更 (gèng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" gèng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"g"}</_components.strong>{" like "}<_components.strong>{"\"g\""}</_components.strong>{" in \"go\""}</_components.li>{"\n"}<_components.li><_components.strong>{"èng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ung\""}</_components.strong>{" in \"hung\", but with fourth tone → sharp fall down"}</_components.li>{"\n"}<_components.li><_components.strong>{"gèng"}</_components.strong>{" sounds like "}<_components.strong>{"\"gung!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (`) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Start high and drop down sharply, like making an emphatic statement. Perfect for expressing \"even\nmore\" emphasis!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"更多 (gèng duō) - \"more; even more\""}</_components.li>{"\n"}<_components.li>{"更好 (gèng hǎo) - \"better; even better\""}</_components.li>{"\n"}<_components.li>{"更加 (gèng jiā) - \"even more; all the more\""}</_components.li>{"\n"}<_components.li>{"更新 (gèng xīn) - \"update; renew\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"📚 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"更 can also be pronounced "}<_components.strong>{"gēng"}</_components.strong>{" (first tone) in some contexts, meaning \"watch\" or \"night watch\"\n(classical usage), but "}<_components.strong>{"gèng"}</_components.strong>{" (fourth tone) meaning \"more\" is much more common in modern Chinese."}</_components.p>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"更 means \"more\" - when you want to emphasize \"even MORE,\" you naturally use that emphatic, falling\nfourth tone: "}<_components.strong>{"\"gèng!\""}</_components.strong></_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
