// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 血 (xuè)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" xuè"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"x"}</_components.strong>{" like "}<_components.strong>{"\"sh\""}</_components.strong>{" in \"sheep\" (but with tongue curled back slightly)"}</_components.li>{"\n"}<_components.li><_components.strong>{"uè"}</_components.strong>{" sounds like "}<_components.strong>{"\"way\""}</_components.strong>{" but shorter, with fourth tone → sharp falling pitch"}</_components.li>{"\n"}<_components.li><_components.strong>{"xuè"}</_components.strong>{" sounds like "}<_components.strong>{"\"shway!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (`) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're making an urgent statement: "}<_components.strong>{"\"xuè!\""}</_components.strong>{" — that's the tone pattern of "}<_components.strong>{"xuè"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"血 (xuè) - \"blood\""}</_components.li>{"\n"}<_components.li>{"血液 (xuè yè) - \"blood (medical term)\""}</_components.li>{"\n"}<_components.li>{"流血 (liú xuè) - \"bleed\""}</_components.li>{"\n"}<_components.li>{"血压 (xuè yā) - \"blood pressure\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"xuè"}</_components.strong>{" as urgently mentioning blood in a medical context: \"Blood!\" — the falling tone\nsounds serious and important."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
