// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 光 (guāng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" guāng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"gu"}</_components.strong>{" like "}<_components.strong>{"\"goo\""}</_components.strong>{" in \"goose\""}</_components.li>{"\n"}<_components.li><_components.strong>{"āng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ahng\""}</_components.strong>{" with a high flat tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"guāng"}</_components.strong>{" sounds like "}<_components.strong>{"\"gwahng\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (¯) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're singing a steady, high note: "}<_components.strong>{"\"guāng...\""}</_components.strong>{" — that's the tone pattern of\n"}<_components.strong>{"guāng"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"光 (guāng) - \"light\""}</_components.li>{"\n"}<_components.li>{"阳光 (yáng guāng) - \"sunlight\""}</_components.li>{"\n"}<_components.li>{"光明 (guāng míng) - \"bright; light\""}</_components.li>{"\n"}<_components.li>{"光线 (guāng xiàn) - \"ray of light\""}</_components.li>{"\n"}<_components.li>{"月光 (yuè guāng) - \"moonlight\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"光 consistently uses the first tone (guāng) in all its common meanings and compounds. The character\nrepresents both physical light and metaphorical concepts of brightness or clarity."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
