// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 八 (bā)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" bā"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"b"}</_components.strong>{" like "}<_components.strong>{"\"b\""}</_components.strong>{" in \"bay\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ā"}</_components.strong>{" sounds like "}<_components.strong>{"\"ah\""}</_components.strong>{" in \"father\" but with a high flat tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"bā"}</_components.strong>{" sounds like "}<_components.strong>{"\"bah\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (¯) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're singing a steady, high note: "}<_components.strong>{"\"bā...\""}</_components.strong>{" — that's the tone pattern of "}<_components.strong>{"bā"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"八 (bā) - \"eight\""}</_components.li>{"\n"}<_components.li>{"八月 (bā yuè) - \"August\""}</_components.li>{"\n"}<_components.li>{"十八 (shí bā) - \"eighteen\""}</_components.li>{"\n"}<_components.li>{"八十 (bā shí) - \"eighty\""}</_components.li>{"\n"}<_components.li>{"八点 (bā diǎn) - \"eight o'clock\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"八 consistently uses the first tone (bā) as the number \"eight.\" In Chinese culture, eight is\nconsidered a lucky number because it sounds similar to 发 (fā), which means \"to prosper\" or \"to\nbecome wealthy.\""}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
