// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 夬 (guài)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" guài"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"g"}</_components.strong>{" like "}<_components.strong>{"\"g\""}</_components.strong>{" in \"go\""}</_components.li>{"\n"}<_components.li><_components.strong>{"uài"}</_components.strong>{" sounds like "}<_components.strong>{"\"why\""}</_components.strong>{", but with fourth tone → sharp falling pitch"}</_components.li>{"\n"}<_components.li><_components.strong>{"guài"}</_components.strong>{" sounds like "}<_components.strong>{"\"gwhy!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (ˋ) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're making a definitive statement: "}<_components.strong>{"\"guài!\""}</_components.strong>{" — that's the sharp, decisive drop of\nthe "}<_components.strong>{"fourth tone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"夬 (guài) - \"parted\" (rare standalone usage)"}</_components.li>{"\n"}<_components.li>{"决 (jué) - contains the 夬 component, meaning \"decide\""}</_components.li>{"\n"}<_components.li>{"快 (kuài) - contains the 夬 component, meaning \"fast\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"夬 is primarily used as a component in other characters rather than as a standalone word. It\nrepresents the concept of \"parted\" or \"divided\" and appears in characters like 决 (decide)\nand 快 (fast). While you may not encounter 夬 alone in everyday conversation, understanding its\npronunciation helps with recognizing it in compound characters."}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Character Component:"}</_components.strong></_components.p>{"\n"}<_components.p>{"As a radical component, 夬 often relates to concepts of separation, decision, or swiftness in the\ncharacters it appears in."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
