// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 温 (wēn)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" wēn"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"w"}</_components.strong>{" like "}<_components.strong>{"\"w\""}</_components.strong>{" in \"way\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ēn"}</_components.strong>{" sounds like "}<_components.strong>{"\"un\""}</_components.strong>{" in \"fun\", but with first tone → high and steady"}</_components.li>{"\n"}<_components.li><_components.strong>{"wēn"}</_components.strong>{" sounds like "}<_components.strong>{"\"when\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're holding a steady note: "}<_components.strong>{"\"wēn\""}</_components.strong>{" — that's the tone pattern of "}<_components.strong>{"wēn"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"温 (wēn) - \"warm/lukewarm\""}</_components.li>{"\n"}<_components.li>{"温度 (wēn dù) - \"temperature\""}</_components.li>{"\n"}<_components.li>{"温暖 (wēn nuǎn) - \"warm\""}</_components.li>{"\n"}<_components.li>{"温柔 (wēn róu) - \"gentle/tender\""}</_components.li>{"\n"}<_components.li>{"温泉 (wēn quán) - \"hot spring\""}</_components.li>{"\n"}<_components.li>{"气温 (qì wēn) - \"air temperature\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"温 (wēn) contains the water radical (氵) on the left. Think of warm water — not too hot, not too\ncold, but just the right lukewarm temperature that feels comfortable!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
