// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 攴 (pū)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" pū"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"p"}</_components.strong>{" like "}<_components.strong>{"\"p\""}</_components.strong>{" in \"put\" (but with a slight puff of air)"}</_components.li>{"\n"}<_components.li><_components.strong>{"ū"}</_components.strong>{" sounds like "}<_components.strong>{"\"oo\""}</_components.strong>{" in \"book\", but held steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"pū"}</_components.strong>{" sounds like "}<_components.strong>{"\"poo\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like singing a steady high note: "}<_components.strong>{"\"pū~~~\""}</_components.strong>{" — that's the flat, steady tone of "}<_components.strong>{"pū"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"攴 (pū) - \"tap; strike\" (radical)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"攴 is primarily used as a "}<_components.strong>{"radical"}</_components.strong>{" (部首) in Chinese characters. It represents the action of\nstriking or tapping and appears in many characters related to actions performed with hands or tools,\nsuch as:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"攻 (gōng) - \"attack\""}</_components.li>{"\n"}<_components.li>{"收 (shōu) - \"receive\""}</_components.li>{"\n"}<_components.li>{"放 (fàng) - \"release\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"\"攴\""}</_components.strong>{" as "}<_components.strong>{"\"poo\""}</_components.strong>{" held steady — like the steady sound of tapping or striking!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
