// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 辶 (chuò)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" chuò"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command: "}<_components.strong>{"\"Stop!\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"ch"}</_components.strong>{" like "}<_components.strong>{"\"ch\""}</_components.strong>{" in \"chair\""}</_components.li>{"\n"}<_components.li><_components.strong>{"uò"}</_components.strong>{" sounds like "}<_components.strong>{"\"woh\""}</_components.strong>{" but with fourth tone → sharp falling tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"chuò"}</_components.strong>{" sounds like "}<_components.strong>{"\"chwoh!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (ˋ) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like giving a firm command: "}<_components.strong>{"\"chuò!\""}</_components.strong>{" — that's the sharp, falling tone pattern of "}<_components.strong>{"chuò"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Note on Usage:"}</_components.strong></_components.p>{"\n"}<_components.p>{"辶 is the "}<_components.strong>{"\"walking\" radical"}</_components.strong>{" (also called 走之底 \"walking bottom\"). It appears at the bottom of\nmany characters related to movement:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"过 (guò) - \"to pass\""}</_components.li>{"\n"}<_components.li>{"这 (zhè) - \"this\""}</_components.li>{"\n"}<_components.li>{"进 (jìn) - \"to enter\""}</_components.li>{"\n"}<_components.li>{"远 (yuǎn) - \"far\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"辶 represents "}<_components.strong>{"walking/movement"}</_components.strong>{" — pronounce it with a sharp, decisive "}<_components.strong>{"chuò"}</_components.strong>{" like taking a firm\nstep forward!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
