// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 难 (nán)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" nán"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"n"}</_components.strong>{" like "}<_components.strong>{"\"n\""}</_components.strong>{" in \"no\""}</_components.li>{"\n"}<_components.li><_components.strong>{"án"}</_components.strong>{" sounds like "}<_components.strong>{"\"ahn\""}</_components.strong>{" but with second tone → rising pitch"}</_components.li>{"\n"}<_components.li><_components.strong>{"nán"}</_components.strong>{" sounds like "}<_components.strong>{"\"nahn?\""}</_components.strong>{" with a questioning rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" (´) is a "}<_components.strong>{"rising"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're struggling and asking \"This is hard?\": "}<_components.strong>{"\"nán?\""}</_components.strong>{" — that rising, questioning tone\nof difficulty."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"难 (nán) - \"difficult, hard\""}</_components.li>{"\n"}<_components.li>{"难过 (nán guò) - \"sad, upset\""}</_components.li>{"\n"}<_components.li>{"困难 (kùn nán) - \"difficulty, hardship\""}</_components.li>{"\n"}<_components.li>{"难题 (nán tí) - \"difficult problem\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"Special Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"难 can also be pronounced "}<_components.strong>{"nàn"}</_components.strong>{" (fourth tone) in some contexts, meaning \"disaster\" or \"calamity,\"\nbut "}<_components.strong>{"nán"}</_components.strong>{" (second tone) meaning \"difficult\" is much more common."}</_components.p>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of your voice rising with frustration when something is difficult - that rising second tone\nperfectly captures the struggle of "}<_components.strong>{"难"}</_components.strong>{" meaning \"difficult\"!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
