// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 叫 (jiào)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" jiào"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"j"}</_components.strong>{" like "}<_components.strong>{"\"j\""}</_components.strong>{" in \"jeep\" (but softer, like \"gee\")"}</_components.li>{"\n"}<_components.li><_components.strong>{"iào"}</_components.strong>{" sounds like "}<_components.strong>{"\"yow\""}</_components.strong>{" (like \"ouch!\") but with fourth tone → sharp falling"}</_components.li>{"\n"}<_components.li><_components.strong>{"jiào"}</_components.strong>{" sounds like "}<_components.strong>{"\"jyow\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (ˋ) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're calling out loudly: "}<_components.strong>{"\"jiào!\""}</_components.strong>{" — that's the commanding tone pattern of "}<_components.strong>{"jiào"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"叫 (jiào) - \"call; shout; be called\""}</_components.li>{"\n"}<_components.li>{"叫什么 (jiào shén me) - \"what is it called?\""}</_components.li>{"\n"}<_components.li>{"我叫... (wǒ jiào...) - \"my name is...\""}</_components.li>{"\n"}<_components.li>{"大叫 (dà jiào) - \"shout loudly\""}</_components.li>{"\n"}<_components.li>{"叫声 (jiào shēng) - \"cry; call; shout\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"\"jyow\""}</_components.strong>{" with a sharp drop — when you "}<_components.strong>{"call"}</_components.strong>{" someone, you often use a strong, falling\nintonation to get their attention!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
