// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p>{"A plural suffix for people; used to indicate a group of people."}</_components.p>{"\n"}<_components.h2>{"Quick Reference"}</_components.h2>{"\n"}<_components.table><_components.thead><_components.tr><_components.th>{"Aspect"}</_components.th><_components.th>{"Info"}</_components.th></_components.tr></_components.thead><_components.tbody><_components.tr><_components.td>{"Pinyin"}</_components.td><_components.td>{"men (neutral tone)"}</_components.td></_components.tr><_components.tr><_components.td>{"Core meaning"}</_components.td><_components.td>{"plural suffix for people"}</_components.td></_components.tr><_components.tr><_components.td>{"Part of speech"}</_components.td><_components.td>{"particle/suffix"}</_components.td></_components.tr><_components.tr><_components.td>{"Tone"}</_components.td><_components.td>{"neutral/light tone"}</_components.td></_components.tr></_components.tbody></_components.table>{"\n"}<_components.h2>{"Visual Breakdown"}</_components.h2>{"\n"}<_components.p>{"们 combines "}<_components.strong>{"person + gate"}</_components.strong>{" to show people gathering."}</_components.p>{"\n"}<_components.table><_components.thead><_components.tr><_components.th>{"Component"}</_components.th><_components.th>{"Visual Description"}</_components.th></_components.tr></_components.thead><_components.tbody><_components.tr><_components.td><_components.strong>{"亻"}</_components.strong></_components.td><_components.td>{"Person radical (人) - indicates this relates to people"}</_components.td></_components.tr><_components.tr><_components.td><_components.strong>{"门"}</_components.strong></_components.td><_components.td>{"Gate (门) - suggests gathering, entrance, or group"}</_components.td></_components.tr></_components.tbody></_components.table>{"\n"}<_components.h2>{"Mnemonic"}</_components.h2>{"\n"}<_components.p>{"Think of 们 as "}<_components.strong>{"people gathering at a gate"}</_components.strong>{":"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"The person radical (亻) shows this is about people"}</_components.li>{"\n"}<_components.li>{"The gate (门) represents a meeting place where people come together"}</_components.li>{"\n"}<_components.li>{"Like people gathering at the village gate or entrance to a building"}</_components.li>{"\n"}<_components.li>{"When you see multiple people at one gate, you know it's a group"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p>{"This suffix transforms singular person words into plural groups: 我 (I) → 我们 (we), 你 (you)\n→ 你们 (you all), 他 (he) → 他们 (they)."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
