// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 克 (kè)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" kè"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"k"}</_components.strong>{" like "}<_components.strong>{"\"k\""}</_components.strong>{" in \"kite\""}</_components.li>{"\n"}<_components.li><_components.strong>{"è"}</_components.strong>{" sounds like "}<_components.strong>{"\"uh\""}</_components.strong>{" in \"duh\" but with a sharp falling tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"kè"}</_components.strong>{" sounds like "}<_components.strong>{"\"kuh!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (`) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're giving a firm command: "}<_components.strong>{"\"kè!\""}</_components.strong>{" — that's the tone pattern of "}<_components.strong>{"kè"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"克 (kè) - \"gram\" (unit of measurement)"}</_components.li>{"\n"}<_components.li>{"千克 (qiān kè) - \"kilogram\""}</_components.li>{"\n"}<_components.li>{"克服 (kè fú) - \"to overcome\""}</_components.li>{"\n"}<_components.li>{"巧克力 (qiǎo kè lì) - \"chocolate\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"克 is commonly used as a unit of measurement (gram) and also appears in words meaning \"to overcome\"\nor \"to conquer.\" The pronunciation remains consistently fourth tone (kè) across all uses."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
