// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 当 (dāng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" dāng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note: "}<_components.strong>{"\"Daaa\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"d"}</_components.strong>{" like "}<_components.strong>{"\"d\""}</_components.strong>{" in \"day\""}</_components.li>{"\n"}<_components.li><_components.strong>{"āng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ahng\""}</_components.strong>{" but with first tone → steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"dāng"}</_components.strong>{" sounds like "}<_components.strong>{"\"dahng\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (¯) is a "}<_components.strong>{"high flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're making a confident statement: "}<_components.strong>{"\"dāng\""}</_components.strong>{" — that's the steady, authoritative tone\nof "}<_components.strong>{"dāng"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"当 (dāng) - \"serve as/act as\""}</_components.li>{"\n"}<_components.li>{"当时 (dāng shí) - \"at that time\""}</_components.li>{"\n"}<_components.li>{"当然 (dāng rán) - \"of course\""}</_components.li>{"\n"}<_components.li>{"当作 (dāng zuò) - \"regard as\""}</_components.li>{"\n"}<_components.li>{"当中 (dāng zhōng) - \"in the middle\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"当 can also be pronounced "}<_components.strong>{"dàng"}</_components.strong>{" (fourth tone) meaning \"proper/suitable\":"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"恰当 (qià dàng) - \"appropriate\""}</_components.li>{"\n"}<_components.li>{"上当 (shàng dàng) - \"be fooled\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"当 means \"serve as\" — the steady first tone sounds confident and authoritative, like someone\n"}<_components.strong>{"taking charge"}</_components.strong>{" of a situation!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
