// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 已 (yǐ)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" yǐ"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"y"}</_components.strong>{" like "}<_components.strong>{"\"y\""}</_components.strong>{" in \"yes\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǐ"}</_components.strong>{" sounds like "}<_components.strong>{"\"ee\""}</_components.strong>{" with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"yǐ"}</_components.strong>{" sounds like "}<_components.strong>{"\"yee\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're confirming something is done: "}<_components.strong>{"\"yǐ...\""}</_components.strong>{" — that contemplative tone shows\ncompletion."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"已 (yǐ) - \"already; to stop\""}</_components.li>{"\n"}<_components.li>{"已经 (yǐ jīng) - \"already\""}</_components.li>{"\n"}<_components.li>{"早已 (zǎo yǐ) - \"long ago; already\""}</_components.li>{"\n"}<_components.li>{"业已 (yè yǐ) - \"already\" (formal)"}</_components.li>{"\n"}<_components.li>{"已故 (yǐ gù) - \"deceased; late\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"已"}</_components.strong>{" as something completed — that "}<_components.strong>{"third tone"}</_components.strong>{" dip and rise shows the finality of\n\"already done\"!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Don't confuse with similar characters:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"己"}</_components.strong>{" (jǐ) - \"oneself\""}</_components.li>{"\n"}<_components.li><_components.strong>{"巳"}</_components.strong>{" (sì) - \"9-11 AM\" (different tone)"}</_components.li>{"\n"}</_components.ul></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
