// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 的 (de)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" de"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Neutral tone"}</_components.strong>{" — "}<_components.strong>{"light and unstressed"}</_components.strong>{", often shortened"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"d"}</_components.strong>{" like "}<_components.strong>{"\"d\""}</_components.strong>{" in \"do\" but "}<_components.strong>{"softer and without a puff"}</_components.strong>{" — tongue touches just behind upper\nteeth"}</_components.li>{"\n"}<_components.li><_components.strong>{"e"}</_components.strong>{" sounds like "}<_components.strong>{"\"uh\""}</_components.strong>{" but very light and quick"}</_components.li>{"\n"}<_components.li><_components.strong>{"de"}</_components.strong>{" sounds like a quick "}<_components.strong>{"\"duh\""}</_components.strong>{" but unstressed"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"neutral tone"}</_components.strong>{" (·) is "}<_components.strong>{"unstressed and light"}</_components.strong>{":"}</_components.p>{"\n"}<_components.p>{"Say it quickly and lightly, like the \"uh\" in \"uh-oh\" — "}<_components.strong>{"de"}</_components.strong>{" should feel effortless and natural."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"我的 (wǒ de) - \"my; mine\""}</_components.li>{"\n"}<_components.li>{"你的 (nǐ de) - \"your; yours\""}</_components.li>{"\n"}<_components.li>{"好的 (hǎo de) - \"okay; good\""}</_components.li>{"\n"}<_components.li>{"红的 (hóng de) - \"red one\""}</_components.li>{"\n"}<_components.li>{"大的 (dà de) - \"big one\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"的 is like the English \"of\" or \"'s\" — it's so common that it's pronounced quickly and lightly, just\nlike how we rush through small words in English!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"的 is one of the most frequently used particles in Chinese, functioning as a possessive marker and\nmodifier. It's almost always pronounced with neutral tone in everyday speech."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
