// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 差 (chà)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" chà"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command: "}<_components.strong>{"\"Cha!\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"ch"}</_components.strong>{" like "}<_components.strong>{"\"ch\""}</_components.strong>{" in \"chair\" with a puff of air"}</_components.li>{"\n"}<_components.li><_components.strong>{"à"}</_components.strong>{" sounds like "}<_components.strong>{"\"ah\""}</_components.strong>{" with a sharp falling tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"chà"}</_components.strong>{" sounds like "}<_components.strong>{"\"cha!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (ˋ) starts "}<_components.strong>{"high"}</_components.strong>{" and drops "}<_components.strong>{"fast"}</_components.strong>{":"}</_components.p>{"\n"}<_components.p>{"Say it like you're expressing disappointment: "}<_components.strong>{"\"chà!\""}</_components.strong>{" — that's the decisive energy of "}<_components.strong>{"chà"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"差 (chà) - \"poor; bad; lacking\""}</_components.li>{"\n"}<_components.li>{"差不多 (chà bu duō) - \"almost; about the same\""}</_components.li>{"\n"}<_components.li>{"差别 (chā bié) - \"difference\" (note: different tone here)"}</_components.li>{"\n"}<_components.li>{"差点儿 (chà diǎn er) - \"almost; nearly\""}</_components.li>{"\n"}<_components.li>{"相差 (xiāng chà) - \"to differ by\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"差 has multiple pronunciations depending on meaning:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"chà"}</_components.strong>{" (4th tone) - \"poor; lacking\""}</_components.li>{"\n"}<_components.li><_components.strong>{"chā"}</_components.strong>{" (1st tone) - \"difference; to differ\""}</_components.li>{"\n"}<_components.li><_components.strong>{"chāi"}</_components.strong>{" (1st tone) - \"to send on errands\""}</_components.li>{"\n"}</_components.ul></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
