// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 亡 (wáng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" wáng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question: "}<_components.strong>{"\"Really?\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"w"}</_components.strong>{" like "}<_components.strong>{"\"w\""}</_components.strong>{" in \"way\""}</_components.li>{"\n"}<_components.li><_components.strong>{"áng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ahng\""}</_components.strong>{" in \"song\" but with a rising tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"wáng"}</_components.strong>{" sounds like "}<_components.strong>{"\"wahng?\""}</_components.strong>{" with a questioning rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip (Second tone: ˊ)"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" is a "}<_components.strong>{"rising"}</_components.strong>{" tone, though the meaning is heavy:"}</_components.p>{"\n"}<_components.p>{"Say it like you're mentioning something serious with concern: "}<_components.strong>{"\"wáng?\""}</_components.strong>{" — that's the rising tone\nwith gravity."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"亡 (wáng) - \"death; to die; to perish\""}</_components.li>{"\n"}<_components.li>{"死亡 (sǐ wáng) - \"death\""}</_components.li>{"\n"}<_components.li>{"亡命 (wáng míng) - \"flee for one's life\""}</_components.li>{"\n"}<_components.li>{"灭亡 (miè wáng) - \"perish; destruction\""}</_components.li>{"\n"}<_components.li>{"流亡 (liú wáng) - \"exile\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"亡"}</_components.strong>{" as a serious topic that raises concern — that's the "}<_components.strong>{"second tone"}</_components.strong>{" rising with\nweight."}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Usage Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"亡 is primarily used in formal or literary contexts. In everyday speech, 死 (sǐ) is more commonly\nused for \"death.\" 亡 often appears in compound words and formal expressions."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
