// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 馆 (guǎn)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" guǎn"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding thoughtfully"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"g"}</_components.strong>{" like "}<_components.strong>{"\"g\""}</_components.strong>{" in \"go\""}</_components.li>{"\n"}<_components.li><_components.strong>{"uǎn"}</_components.strong>{" sounds like "}<_components.strong>{"\"wahn\""}</_components.strong>{" but with the third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"guǎn"}</_components.strong>{" sounds like "}<_components.strong>{"\"gwahn\""}</_components.strong>{" with a dip-then-rise pattern"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone. Start middle, dip down low, then rise back up -\nlike you're thoughtfully considering a place to visit."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"图书馆 (tú shū guǎn) - \"library\""}</_components.li>{"\n"}<_components.li>{"博物馆 (bó wù guǎn) - \"museum\""}</_components.li>{"\n"}<_components.li>{"体育馆 (tǐ yù guǎn) - \"gymnasium\""}</_components.li>{"\n"}<_components.li>{"饭馆 (fàn guǎn) - \"restaurant\""}</_components.li>{"\n"}<_components.li>{"旅馆 (lǚ guǎn) - \"hotel, inn\""}</_components.li>{"\n"}<_components.li>{"茶馆 (chá guǎn) - \"teahouse\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"When you're deciding which museum or library to visit and think \"Hmm, which one...\" - that\ncontemplative tone matches the dip-and-rise third tone of "}<_components.strong>{"guǎn"}</_components.strong>{"."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
