// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 网 (wǎng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" wǎng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"w"}</_components.strong>{" like "}<_components.strong>{"\"w\""}</_components.strong>{" in \"way\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǎng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ang\""}</_components.strong>{" in \"hang\", but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"wǎng"}</_components.strong>{" sounds like "}<_components.strong>{"\"wahng\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're thinking about a web or network: "}<_components.strong>{"\"wǎng...\""}</_components.strong>{" — that contemplative dip and rise."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"网上 (wǎng shàng) - \"online; on the internet\""}</_components.li>{"\n"}<_components.li>{"网站 (wǎng zhàn) - \"website\""}</_components.li>{"\n"}<_components.li>{"网球 (wǎng qiú) - \"tennis\""}</_components.li>{"\n"}<_components.li>{"网络 (wǎng luò) - \"network\""}</_components.li>{"\n"}<_components.li>{"上网 (shàng wǎng) - \"to go online\""}</_components.li>{"\n"}<_components.li>{"互联网 (hù lián wǎng) - \"internet\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"A "}<_components.strong>{"net"}</_components.strong>{" or "}<_components.strong>{"web"}</_components.strong>{" has that interconnected, thoughtful pattern — just like the dip-and-rise of the\nthird tone!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
