// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 耒 (lěi)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" lěi"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"hmm\" when thinking"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"l"}</_components.strong>{" like "}<_components.strong>{"\"l\""}</_components.strong>{" in \"love\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ěi"}</_components.strong>{" sounds like "}<_components.strong>{"\"ay\""}</_components.strong>{" in \"say\", but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"lěi"}</_components.strong>{" sounds like "}<_components.strong>{"\"lay\""}</_components.strong>{" with a contemplative dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're considering an ancient farming tool: "}<_components.strong>{"\"lěi...\""}</_components.strong>{" — that's the thoughtful tone\npattern of "}<_components.strong>{"lěi"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"耒 (lěi) - \"plow\" (ancient farming tool)"}</_components.li>{"\n"}<_components.li>{"耒耜 (lěi sì) - \"plow and spade\" (traditional farming implements)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"Special Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"耒 is primarily seen as a "}<_components.strong>{"radical"}</_components.strong>{" in other characters related to farming and agriculture. As a\nstandalone character, it's quite rare in modern usage but appears in:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"Characters like 耕 (gēng) - \"to plow, cultivate\""}</_components.li>{"\n"}<_components.li>{"Characters like 耘 (yún) - \"to weed\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of the ancient, thoughtful work of plowing fields — "}<_components.strong>{"lěi"}</_components.strong>{" carries that deep, contemplative\nthird tone of agricultural tradition!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
