// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 诉 (sù)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" sù"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — "}<_components.strong>{"falling"}</_components.strong>{" tone, like a firm command: "}<_components.strong>{"\"soo!\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"s"}</_components.strong>{" like "}<_components.strong>{"\"s\""}</_components.strong>{" in \"see\" — crisp and clear"}</_components.li>{"\n"}<_components.li><_components.strong>{"ù"}</_components.strong>{" sounds like "}<_components.strong>{"\"oo\""}</_components.strong>{" in \"zoo\" but with a falling tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"sù"}</_components.strong>{" sounds like "}<_components.strong>{"\"soo!\""}</_components.strong>{" with a decisive drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔊 Key Sound Tips:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"s"}</_components.strong>{" in Chinese is "}<_components.strong>{"clean and sharp"}</_components.strong>{" — make sure your tongue doesn't touch your teeth, keep\nit behind your lower teeth for a crisp sound."}</_components.p>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (`) is a "}<_components.strong>{"falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Start "}<_components.strong>{"high and drop down sharply"}</_components.strong>{" like giving a firm command: "}<_components.strong>{"\"sù!\""}</_components.strong></_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"诉 (sù) - \"accuse; tell; complain\""}</_components.li>{"\n"}<_components.li>{"告诉 (gào sù) - \"tell; inform\""}</_components.li>{"\n"}<_components.li>{"起诉 (qǐ sù) - \"sue; prosecute\""}</_components.li>{"\n"}<_components.li>{"诉说 (sù shuō) - \"tell; relate\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think "}<_components.strong>{"\"sue!\""}</_components.strong>{" with that sharp falling tone — like firmly declaring you're going to sue someone!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
