// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 黄 (huáng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" huáng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"hu"}</_components.strong>{" like "}<_components.strong>{"\"who\""}</_components.strong>{" but shorter"}</_components.li>{"\n"}<_components.li><_components.strong>{"áng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ahng\""}</_components.strong>{" with a rising tone, similar to \"hung\" but with an \"ah\" sound"}</_components.li>{"\n"}<_components.li><_components.strong>{"huáng"}</_components.strong>{" sounds like "}<_components.strong>{"\"hwahng\""}</_components.strong>{" with a rising pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" (ˊ) is a "}<_components.strong>{"rising"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're asking about the color: "}<_components.strong>{"\"huáng?\""}</_components.strong>{" — that rising, questioning intonation when\nyou see something yellow."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"黄 (huáng) - \"yellow\""}</_components.li>{"\n"}<_components.li>{"黄色 (huáng sè) - \"yellow color\""}</_components.li>{"\n"}<_components.li>{"黄金 (huáng jīn) - \"gold\""}</_components.li>{"\n"}<_components.li>{"黄河 (huáng hé) - \"Yellow River\""}</_components.li>{"\n"}<_components.li>{"黄瓜 (huáng guā) - \"cucumber\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"黄 sounds like \"hwang\" with a rising tone — imagine pointing at something yellow and asking\n"}<_components.strong>{"\"huáng?\""}</_components.strong>{" with that questioning rise, like \"Yellow?\""}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
