// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 好 (hǎo)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" hǎo"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"h"}</_components.strong>{" like "}<_components.strong>{"\"h\""}</_components.strong>{" in \"hat\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǎo"}</_components.strong>{" sounds a bit like "}<_components.strong>{"\"how\""}</_components.strong>{", but with the "}<_components.strong>{"third tone"}</_components.strong>{" → dip down and rise up."}</_components.li>{"\n"}<_components.li><_components.strong>{"hǎo"}</_components.strong>{" sounds like "}<_components.strong>{"\"how\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're thinking or being thoughtful: "}<_components.strong>{"\"hǎo...\""}</_components.strong>{" — that's the tone pattern of "}<_components.strong>{"hǎo"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Note on Usage:"}</_components.strong></_components.p>{"\n"}<_components.p>{"好 (hǎo) has two main meanings:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"好 (hǎo)"}</_components.strong>{" - \"good; nice; friendly\" (third tone)"}</_components.li>{"\n"}<_components.li><_components.strong>{"好 (hǎo)"}</_components.strong>{" - \"to like; to enjoy\" (third tone)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p>{"Both meanings use the same pronunciation "}<_components.strong>{"hǎo"}</_components.strong>{" with third tone. However, in some compound words\nexpressing preference/fondness, 好 may be pronounced with fourth tone (hào), such as in:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"好奇"}</_components.strong>{" (hào qí) - \"curious\""}</_components.li>{"\n"}<_components.li><_components.strong>{"爱好"}</_components.strong>{" (ài hào) - \"hobby\""}</_components.li>{"\n"}<_components.li><_components.strong>{"好学"}</_components.strong>{" (hào xué) - \"studious\""}</_components.li>{"\n"}</_components.ul></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
