// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 歹 (dǎi)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" dǎi"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"d"}</_components.strong>{" like "}<_components.strong>{"\"d\""}</_components.strong>{" in \"dog\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǎi"}</_components.strong>{" sounds like "}<_components.strong>{"\"eye\""}</_components.strong>{" with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"dǎi"}</_components.strong>{" sounds like "}<_components.strong>{"\"die\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're contemplating something ominous: "}<_components.strong>{"\"dǎi...\""}</_components.strong>{" — that thoughtful dip-then-rise\npattern."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"歹徒 (dǎi tú) - \"bad person; criminal\""}</_components.li>{"\n"}<_components.li>{"歹意 (dǎi yì) - \"malice; ill intent\""}</_components.li>{"\n"}<_components.li>{"好歹 (hǎo dǎi) - \"good or bad; anyway\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"歹 is primarily used as a "}<_components.strong>{"radical component"}</_components.strong>{" in other characters and rarely appears alone in\nmodern Chinese. It's the \"bad/evil\" radical found in characters like:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"死 (sǐ) - \"die\" (contains 歹)"}</_components.li>{"\n"}<_components.li>{"残 (cán) - \"cruel\" (contains 歹)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"歹 represents \"death/evil\" — say it with that "}<_components.strong>{"contemplative dip-and-rise"}</_components.strong>{" like pondering\nsomething dark!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
