// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 无 (wú)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" wú"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"w"}</_components.strong>{" like "}<_components.strong>{"\"w\""}</_components.strong>{" in \"way\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ú"}</_components.strong>{" sounds like "}<_components.strong>{"\"oo\""}</_components.strong>{" in \"moon\" but with second tone → rising tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"wú"}</_components.strong>{" sounds like "}<_components.strong>{"\"woo?\""}</_components.strong>{" with a questioning rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" (´) is a "}<_components.strong>{"rising"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're expressing surprise at the absence of something: "}<_components.strong>{"\"wú?\""}</_components.strong>{" — that rising tone\ncaptures the questioning nature of \"nothing there?\""}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"无 (wú) - \"not have, without, none\""}</_components.li>{"\n"}<_components.li>{"无法 (wú fǎ) - \"unable to, no way to\""}</_components.li>{"\n"}<_components.li>{"无聊 (wú liáo) - \"boring, bored\""}</_components.li>{"\n"}<_components.li>{"无论 (wú lùn) - \"regardless of, no matter\""}</_components.li>{"\n"}<_components.li>{"无所谓 (wú suǒ wèi) - \"doesn't matter, indifferent\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"When you discover there's "}<_components.strong>{"nothing"}</_components.strong>{" there, your voice rises in surprise — just like the rising\nsecond tone of "}<_components.strong>{"wú"}</_components.strong>{"!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Usage Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"无 is a versatile negation character, often used in formal or literary contexts. It's more formal\nthan 没有 (not have) in everyday speech."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
