// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 曼 (màn)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" màn"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"m"}</_components.strong>{" like "}<_components.strong>{"\"m\""}</_components.strong>{" in \"man\""}</_components.li>{"\n"}<_components.li><_components.strong>{"àn"}</_components.strong>{" sounds like "}<_components.strong>{"\"ahn\""}</_components.strong>{", but with fourth tone → sharp fall down"}</_components.li>{"\n"}<_components.li><_components.strong>{"màn"}</_components.strong>{" sounds like "}<_components.strong>{"\"mahn!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (`) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Start high and drop down sharply, like making a definitive statement. The tone matches the graceful,\nflowing meaning of the character."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"曼妙 (màn miào) - \"graceful; enchanting\""}</_components.li>{"\n"}<_components.li>{"曼延 (màn yán) - \"extend; stretch\""}</_components.li>{"\n"}<_components.li>{"浪漫 (làng màn) - \"romantic\""}</_components.li>{"\n"}<_components.li>{"曼哈顿 (Màn hā dùn) - \"Manhattan\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"📚 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"曼 often appears in names and poetic expressions. It conveys a sense of graceful extension or\nflowing beauty."}</_components.p>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"曼 means \"long\" or \"graceful\" - imagine something gracefully extending with that definitive fourth\ntone: "}<_components.strong>{"\"màn!\""}</_components.strong></_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
