fileGroups:
  config:
    - "/.gitignore"
    - "/.prettierignore"
  sources:
    - "**/*"
    - "!dist/**"

tasks:
  prettier:
    command: yarn prettier --write --check --ignore-path .gitignore --ignore-path $workspaceRoot/.gitignore --ignore-path $workspaceRoot/.prettierignore .
    inputs:
      - "@globs(sources)"
      - "@group(config)"
    options:
      runInCI: false

  prettierCheck:
    command: yarn prettier --check --ignore-path .gitignore --ignore-path $workspaceRoot/.gitignore --ignore-path $workspaceRoot/.prettierignore .
    inputs:
      - "@globs(sources)"
      - "@group(config)"
