tasks:
  lint:
    command: eslint . --cache
    inputs:
      # Config files anywhere within the project
      - "**/*.{cjs,js,mjs,json,ts,tsx}"
      - "*.{cjs,js,mjs,json,ts,tsx}"
      # Environment variables
      - "$ESLINT_CACHE"
      - "$ESLINT_*"
    deps:
      - eslint-rules:src
    toolchain: "node"
    env:
      NODE_OPTIONS: --import tsx --experimental-sqlite $NODE_OPTIONS
