tasks:
  lint:
    command: yarn eslint . --cache
    inputs:
      # Config files anywhere within the project
      - "**/*.{cjs,js,mjs,json,ts,tsx}"
      - "*.{cjs,js,mjs,json,ts,tsx}"
      # Environment variables
      - "$ESLINT_CACHE"
      - "$ESLINT_*"
