tasks:
  lint:
    description: "Run ESLint and fix errors (unless in CI)."
    # Auto-fixing errors outside CI is intended to make this more AI-agent friendly.
    script: |
      [ -z ${CI:-} ] && CACHE_FLAG="--cache"
      [ -z ${CI:-} ] && FIX_FLAG="--fix"

      eslint . ${CACHE_FLAG:-} ${FIX_FLAG:-}
    inputs:
      # Config files anywhere within the project
      - "**/*.{cjs,js,mjs,json,ts,tsx}"
      - "*.{cjs,js,mjs,json,ts,tsx}"
      # Environment variables
      - "$CI"
      - "$DEBUG"
      - "$ESLINT_*"
      - "$TIMING"
    deps:
      - eslint-rules:src
    toolchain: "node"
    env:
      NODE_OPTIONS: --import tsx --experimental-sqlite $NODE_OPTIONS
