fileGroups:
  config:
    - "/.gitignore"
    - "/.prettierignore"
  sources:
    - "**/*"
    - "!dist/**"

tasks:
  prettier:
    description: "Run Prettier and fix code formatting issues (except in CI)."
    script: |
      [ -z ${CI:-} ] && WRITE_FLAG="--write"

      yarn prettier ${WRITE_FLAG:-} --check --ignore-path .gitignore --ignore-path $workspaceRoot/.gitignore --ignore-path $workspaceRoot/.prettierignore . '!projects/**'
    inputs:
      - "@globs(sources)"
      - "@group(config)"
      - "!./projects/**/*"
      # Environment variables
      - "$CI"
