inheritedBy:
  tag: vitest-bench

tasks:
  bench:
    tags:
      - ci-daily
    command: vitest bench
    inputs:
      - "**/*"
      - "/yarn.lock" # Dependencies can change behaviour
    env:
      NODE_OPTIONS: --experimental-sqlite $NODE_OPTIONS
    options:
      cache: false
    toolchains: "node"
