// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 强 (qiáng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" qiáng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"q"}</_components.strong>{" like "}<_components.strong>{"\"ch\""}</_components.strong>{" in \"cheese\" (aspirated)"}</_components.li>{"\n"}<_components.li><_components.strong>{"iáng"}</_components.strong>{" sounds like "}<_components.strong>{"\"yahng\""}</_components.strong>{" but with second tone → rising up"}</_components.li>{"\n"}<_components.li><_components.strong>{"qiáng"}</_components.strong>{" sounds like "}<_components.strong>{"\"chahng?\""}</_components.strong>{" with a rising tone"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" (´) is a "}<_components.strong>{"rising"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're impressed by someone's strength: "}<_components.strong>{"\"qiáng?\""}</_components.strong>{" — that's the rising, admiring tone\nof "}<_components.strong>{"qiáng"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"强 (qiáng) - \"strong/powerful\""}</_components.li>{"\n"}<_components.li>{"强壮 (qiáng zhuàng) - \"strong/robust\""}</_components.li>{"\n"}<_components.li>{"坚强 (jiān qiáng) - \"strong/resilient\""}</_components.li>{"\n"}<_components.li>{"强调 (qiáng diào) - \"emphasize\""}</_components.li>{"\n"}<_components.li>{"增强 (zēng qiáng) - \"strengthen\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"强 can also be pronounced "}<_components.strong>{"qiǎng"}</_components.strong>{" (third tone) meaning \"force/compel\":"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"勉强 (miǎn qiǎng) - \"reluctant/forced\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"强 means \"strong\" — the rising second tone sounds like expressing admiration for someone's\n"}<_components.strong>{"impressive strength"}</_components.strong>{"!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
