// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 爸 (bà)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" bà"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"b"}</_components.strong>{" like "}<_components.strong>{"\"b\""}</_components.strong>{" in \"baby\""}</_components.li>{"\n"}<_components.li><_components.strong>{"à"}</_components.strong>{" sounds like "}<_components.strong>{"\"ah\""}</_components.strong>{" but with a sharp falling tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"bà"}</_components.strong>{" sounds like "}<_components.strong>{"\"bah!\""}</_components.strong>{" with a sharp downward drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (`) is a "}<_components.strong>{"falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're calling \"Dad!\" when you want his attention — "}<_components.strong>{"\"bà!\""}</_components.strong>{" — that strong, definitive\ndrop is the fourth tone pattern."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"爸 (bà) - \"dad; father\""}</_components.li>{"\n"}<_components.li>{"爸爸 (bà ba) - \"daddy; father\" (second 爸 is neutral tone)"}</_components.li>{"\n"}<_components.li>{"爸妈 (bà mā) - \"mom and dad\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"In 爸爸 (daddy), the first 爸 is pronounced "}<_components.strong>{"bà"}</_components.strong>{" (fourth tone) and the second 爸 is "}<_components.strong>{"ba"}</_components.strong>{"\n(neutral tone). This is the most common way to say \"father\" in everyday speech."}</_components.p>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"When calling your dad, you use a clear, strong voice to get his attention — just like the fourth\ntone's commanding pattern in 爸!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
