// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p>{"The number seven; the seventh in a sequence."}</_components.p>{"\n"}<_components.h2>{"Quick Reference"}</_components.h2>{"\n"}<_components.p>{"| Aspect         | Info                   |\n| -------------- | ---------------------- |\n| Pinyin         | qī                     |\n| Core meaning   | seven; seventh         |\n| Part of speech | number, adjective      |\n| Tone           | first tone (high flat) |"}</_components.p>{"\n"}<_components.h2>{"Visual Breakdown"}</_components.h2>{"\n"}<_components.p>{"七 represents "}<_components.strong>{"seven as a cut or division"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p>{"| Component | Visual Description                                           |\n| --------- | ------------------------------------------------------------ |\n| "}<_components.strong>{"七"}</_components.strong>{"    | A horizontal line with a bent hook, like cutting or dividing |"}</_components.p>{"\n"}<_components.h2>{"Mnemonic"}</_components.h2>{"\n"}<_components.p>{"Think of 七 as "}<_components.strong>{"a knife making a cutting motion"}</_components.strong>{":"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"The horizontal stroke (一) represents a cutting edge"}</_components.li>{"\n"}<_components.li>{"The bent hook shows the completion of a cut or slice"}</_components.li>{"\n"}<_components.li>{"Like cutting something into seven pieces"}</_components.li>{"\n"}<_components.li>{"Or imagine a sickle (镰刀) making a curved cutting motion"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p>{"This captures the concept of seven through the action of cutting/dividing, suggesting precision and\ncompletion."}</_components.p>{"\n"}<_components.h2>{"Usage Examples"}</_components.h2>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"七天"}</_components.strong>{" (qī tiān) - \"seven days; one week\""}</_components.li>{"\n"}<_components.li><_components.strong>{"七月"}</_components.strong>{" (qī yuè) - \"July\""}</_components.li>{"\n"}<_components.li><_components.strong>{"第七"}</_components.strong>{" (dì qī) - \"seventh\""}</_components.li>{"\n"}<_components.li><_components.strong>{"七十"}</_components.strong>{" (qī shí) - \"seventy\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.h2>{"Cultural Notes"}</_components.h2>{"\n"}<_components.p>{"Seven is considered a lucky number in Chinese culture:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"七夕"}</_components.strong>{" (qī xī) - Chinese Valentine's Day (7th day of 7th lunar month)"}</_components.li>{"\n"}<_components.li>{"Associated with completeness and spiritual significance"}</_components.li>{"\n"}<_components.li>{"Important in traditional astronomy and calendar systems"}</_components.li>{"\n"}</_components.ul></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
