name: 📦 Install dependencies
description: Install dependencies used for all other workflows.

runs:
  using: composite
  steps:
    - name: Enable Corepack
      run: npm i -g corepack@0.33.0
      shell: bash

    # Necessary to run pnpm as part of building the projects/app/api functions
    # for Vercel, because it includes a patch on one of the dependencies. It
    # uses pnpm because Vercel only supports Yarn 1 which doesn't have patch
    # support.
    - name: Enable pnpm
      run: corepack enable pnpm
      shell: bash

    - name: 📦 Install Moon toolchain
      uses: moonrepo/setup-toolchain@v0.4.1
      with:
        auto-install: true

    - name: Yarn install
      run: yarn install
      shell: bash

    - name: Install ffmpeg (for tests)
      run: sudo apt-get install -y ffmpeg
      shell: bash
