name: 📦 Install dependencies
description: Install dependencies used for all other workflows.

runs:
  using: composite
  steps:
    - name: 📦 Install Moon toolchain
      uses: moonrepo/setup-toolchain@v0.5.0
      with:
        auto-install: true
      env:
        DO_NOT_TRACK: 1
        PROTO_TELEMETRY: off
        MOON_DISABLE_TELEMETRY: 1

    - name: Yarn install
      run: yarn install
      shell: bash
      env:
        DO_NOT_TRACK: 1
        PROTO_TELEMETRY: off
        MOON_DISABLE_TELEMETRY: 1

    - name: Install ffmpeg (for tests)
      # Installing from a static build is dramatically faster than using apt-get.
      run: |
        tar -xf ffmpeg-release-i686-static.tar.xz
        echo "${PWD}"/ffmpeg-*-static >> "${GITHUB_PATH}"
      shell: bash
      working-directory: .github/actions/setup-tools
