name: 📦 Install dependencies
description: Install dependencies used for all other workflows.

runs:
  using: composite
  steps:
    - name: 📦 Install Moon toolchain
      uses: moonrepo/setup-toolchain@v0.6.0
      with:
        auto-install: true

    - uses: actions/cache@v4
      with:
        path: .yarn/cache
        key: yarn-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-cache-${{ runner.os }}-

    - name: Yarn install
      run: yarn install
      env:
        YARN_CACHE_FOLDER: .yarn/cache
        YARN_ENABLE_GLOBAL_CACHE: "0"
        # Run hardened mode only if the PR head repo is a fork
        YARN_ENABLE_HARDENED_MODE: ${{ github.event.pull_request.head.repo.fork && '1' || '0' }}
      shell: bash

    - name: Install ffmpeg (for tests)
      # Installing from a static build is dramatically faster than using apt-get.
      run: |
        tar -xf ffmpeg-release-i686-static.tar.xz
        echo "${PWD}"/ffmpeg-*-static >> "${GITHUB_PATH}"
      shell: bash
      working-directory: .github/actions/setup-tools
