// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 花 (huā)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" huā"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"h"}</_components.strong>{" like "}<_components.strong>{"\"h\""}</_components.strong>{" in \"hat\""}</_components.li>{"\n"}<_components.li><_components.strong>{"uā"}</_components.strong>{" sounds like "}<_components.strong>{"\"wah\""}</_components.strong>{" but with first tone → steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"huā"}</_components.strong>{" sounds like "}<_components.strong>{"\"hwah\""}</_components.strong>{" held steady and high"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip (First tone: ˉ)"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" is "}<_components.strong>{"high and flat"}</_components.strong>{", like singing a steady note:"}</_components.p>{"\n"}<_components.p>{"Say it like you're admiring a flower: "}<_components.strong>{"\"huā\""}</_components.strong>{" — that steady, high pitch is the "}<_components.strong>{"first tone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"花 (huā) - \"flower\""}</_components.li>{"\n"}<_components.li>{"花园 (huā yuán) - \"garden\""}</_components.li>{"\n"}<_components.li>{"鲜花 (xiān huā) - \"fresh flowers\""}</_components.li>{"\n"}<_components.li>{"花朵 (huā duǒ) - \"flower blossom\""}</_components.li>{"\n"}<_components.li>{"花费 (huā fèi) - \"to spend, cost\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"花"}</_components.strong>{" as the beautiful, steady blooming of a flower — that constant, high beauty matches\nthe "}<_components.strong>{"first tone"}</_components.strong>{"!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Cultural Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"花 is beloved in Chinese culture, appearing in poetry, art, and festivals. Different flowers have\nsymbolic meanings, like 梅花 (plum blossom) representing resilience."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
