// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 国 (guó)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" guó"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question: "}<_components.strong>{"\"Really?\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"g"}</_components.strong>{" like "}<_components.strong>{"\"g\""}</_components.strong>{" in \"go\""}</_components.li>{"\n"}<_components.li><_components.strong>{"uó"}</_components.strong>{" sounds like "}<_components.strong>{"\"waw\""}</_components.strong>{", but with second tone → rising pitch"}</_components.li>{"\n"}<_components.li><_components.strong>{"guó"}</_components.strong>{" sounds like "}<_components.strong>{"\"gwaw?\""}</_components.strong>{" with a questioning rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" (ˊ) starts "}<_components.strong>{"low"}</_components.strong>{" and rises "}<_components.strong>{"up"}</_components.strong>{":"}</_components.p>{"\n"}<_components.p>{"Say it like you're asking about a country: "}<_components.strong>{"\"guó?\""}</_components.strong>{" — that's the rising tone of "}<_components.strong>{"guó"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"国 (guó) - \"country; nation\""}</_components.li>{"\n"}<_components.li>{"国家 (guó jiā) - \"country; nation\""}</_components.li>{"\n"}<_components.li>{"中国 (zhōng guó) - \"China\""}</_components.li>{"\n"}<_components.li>{"美国 (měi guó) - \"America; USA\""}</_components.li>{"\n"}<_components.li>{"国际 (guó jì) - \"international\""}</_components.li>{"\n"}<_components.li>{"外国 (wài guó) - \"foreign country\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"国"}</_components.strong>{" (country) like proudly asking \"guó?\" — questioning which nation someone's from!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
