// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 种 (zhǒng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" zhǒng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"zh"}</_components.strong>{" like "}<_components.strong>{"\"j\""}</_components.strong>{" in \"judge\" but with tongue tip curled back"}</_components.li>{"\n"}<_components.li><_components.strong>{"ǒng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ong\""}</_components.strong>{" in \"song\", but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"zhǒng"}</_components.strong>{" sounds like "}<_components.strong>{"\"jong\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're thinking or being thoughtful: "}<_components.strong>{"\"zhǒng...\""}</_components.strong>{" — that's the contemplative\ndip-and-rise of "}<_components.strong>{"zhǒng"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Note on Pronunciation:"}</_components.strong></_components.p>{"\n"}<_components.p>{"种 has two pronunciations:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"种 (zhǒng)"}</_components.strong>{" - \"type; kind; species\" (third tone)"}</_components.li>{"\n"}<_components.li><_components.strong>{"种 (zhòng)"}</_components.strong>{" - \"to plant; to grow\" (fourth tone)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"📝 Common Examples with zhǒng:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"种 (zhǒng) - \"type; kind\""}</_components.li>{"\n"}<_components.li>{"各种 (gè zhǒng) - \"various types\""}</_components.li>{"\n"}<_components.li>{"种子 (zhǒng zi) - \"seed\""}</_components.li>{"\n"}<_components.li>{"种族 (zhǒng zú) - \"race; ethnicity\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"For the \"type/kind\" meaning, think of the third tone's thoughtful quality — you're contemplating\ndifferent "}<_components.strong>{"types"}</_components.strong>{" of things."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
