// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 斤 (jīn)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" jīn"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note: "}<_components.strong>{"\"Jeen\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"j"}</_components.strong>{" like "}<_components.strong>{"\"j\""}</_components.strong>{" in \"jeep\""}</_components.li>{"\n"}<_components.li><_components.strong>{"īn"}</_components.strong>{" sounds like "}<_components.strong>{"\"een\""}</_components.strong>{" in \"seen\" but with first tone → high and steady"}</_components.li>{"\n"}<_components.li><_components.strong>{"jīn"}</_components.strong>{" sounds like "}<_components.strong>{"\"jeen\""}</_components.strong>{" with a high, flat pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (¯) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're stating a weight precisely: "}<_components.strong>{"\"jīn...\""}</_components.strong>{" — that's the steady, confident tone\npattern of "}<_components.strong>{"jīn"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"斤 (jīn) - \"jin\" (500 grams, Chinese catty)"}</_components.li>{"\n"}<_components.li>{"公斤 (gōng jīn) - \"kilogram\""}</_components.li>{"\n"}<_components.li>{"半斤 (bàn jīn) - \"half a jin\" (250 grams)"}</_components.li>{"\n"}<_components.li>{"三斤 (sān jīn) - \"three jin\" (1.5 kg)"}</_components.li>{"\n"}<_components.li>{"几斤 (jǐ jīn) - \"how many jin?\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p><_components.strong>{"Jin"}</_components.strong>{" with the steady first tone — like confidently stating the weight at a market!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Cultural Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"斤 is still commonly used in Chinese markets and cooking. One 斤 equals 500 grams or 1.1 pounds.\nIt's essential for shopping for groceries and understanding recipes in Chinese."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
