// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 乐 (lè)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" lè"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like exclaiming: "}<_components.strong>{"\"Yeah!\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"l"}</_components.strong>{" like "}<_components.strong>{"\"l\""}</_components.strong>{" in \"love\""}</_components.li>{"\n"}<_components.li><_components.strong>{"è"}</_components.strong>{" sounds like "}<_components.strong>{"\"eh\""}</_components.strong>{" in \"met\" but with a sharp falling tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"lè"}</_components.strong>{" sounds like "}<_components.strong>{"\"leh!\""}</_components.strong>{" with a sharp drop"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (ˋ) is "}<_components.strong>{"enthusiastic and definitive"}</_components.strong>{":"}</_components.p>{"\n"}<_components.p>{"Say it like you're excited about being happy — "}<_components.strong>{"\"Lè!\""}</_components.strong>{" — that sharp tone matches the joy!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"乐 (lè) - \"happy, joyful\""}</_components.li>{"\n"}<_components.li>{"快乐 (kuài lè) - \"happy\""}</_components.li>{"\n"}<_components.li>{"欢乐 (huān lè) - \"joyful\""}</_components.li>{"\n"}<_components.li>{"乐观 (lè guān) - \"optimistic\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"📍 Note on Multiple Pronunciations:"}</_components.strong></_components.p>{"\n"}<_components.p>{"乐 also has another pronunciation "}<_components.strong>{"yuè"}</_components.strong>{" (fourth tone) when it means "}<_components.strong>{"\"music\""}</_components.strong>{":"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"音乐 (yīn yuè) - \"music\""}</_components.li>{"\n"}<_components.li>{"乐器 (yuè qì) - \"musical instrument\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p><_components.strong>{"Happy"}</_components.strong>{" = "}<_components.strong>{"lè"}</_components.strong>{" with a sharp, decisive tone — like declaring your joy with confidence!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
