// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 穿 (chuān)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" chuān"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note: "}<_components.strong>{"\"Ahhh\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"ch"}</_components.strong>{" like "}<_components.strong>{"\"ch\""}</_components.strong>{" in \"church\""}</_components.li>{"\n"}<_components.li><_components.strong>{"uān"}</_components.strong>{" sounds like "}<_components.strong>{"\"wan\""}</_components.strong>{" in \"wander\", but with first tone → steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"chuān"}</_components.strong>{" sounds like "}<_components.strong>{"\"chwan\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and steady"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Keep your voice high and flat throughout: "}<_components.strong>{"\"chuān\""}</_components.strong>{" — like holding a steady musical note."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"穿 (chuān) - \"wear; put on\""}</_components.li>{"\n"}<_components.li>{"穿衣服 (chuān yī fu) - \"put on clothes\""}</_components.li>{"\n"}<_components.li>{"穿鞋 (chuān xié) - \"put on shoes\""}</_components.li>{"\n"}<_components.li>{"穿过 (chuān guò) - \"go through; pass through\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"\"chwan\""}</_components.strong>{" as the sound of putting on clothes — steady and continuous, like the first\ntone!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
