// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 它 (tā)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" tā"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"t"}</_components.strong>{" like "}<_components.strong>{"\"t\""}</_components.strong>{" in \"top\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ā"}</_components.strong>{" sounds like "}<_components.strong>{"\"ah\""}</_components.strong>{" in \"father\" but held steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"tā"}</_components.strong>{" sounds like "}<_components.strong>{"\"tah\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're clearly pointing to something: "}<_components.strong>{"\"tā!\""}</_components.strong>{" — that steady, high tone is perfect for\n"}<_components.strong>{"it"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"它 (tā) - \"it\" (for animals and things)"}</_components.li>{"\n"}<_components.li>{"它们 (tā men) - \"they/them\" (for animals and things)"}</_components.li>{"\n"}<_components.li>{"它的 (tā de) - \"its\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"📍 Usage Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Chinese has different pronouns for different contexts:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"他 (tā) - \"he/him\" (for males)"}</_components.li>{"\n"}<_components.li>{"她 (tā) - \"she/her\" (for females)"}</_components.li>{"\n"}<_components.li>{"它 (tā) - \"it\" (for animals and things)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p>{"All three are pronounced exactly the same ("}<_components.strong>{"tā"}</_components.strong>{"), but written differently!"}</_components.p>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p><_components.strong>{"It"}</_components.strong>{" — the steady first tone is like confidently pointing at an object: \""}<_components.strong>{"it"}</_components.strong>{"!\""}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
