// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 矢 (shǐ)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" shǐ"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"sh"}</_components.strong>{" like "}<_components.strong>{"\"sh\""}</_components.strong>{" in \"she\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǐ"}</_components.strong>{" sounds like "}<_components.strong>{"\"ee\""}</_components.strong>{" in \"see\" but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"shǐ"}</_components.strong>{" sounds like "}<_components.strong>{"\"shee\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're aiming carefully: "}<_components.strong>{"\"shǐ...\""}</_components.strong>{" — that contemplative tone pattern of "}<_components.strong>{"shǐ"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"矢 (shǐ) - \"arrow\""}</_components.li>{"\n"}<_components.li>{"矢量 (shǐ liàng) - \"vector\" (mathematics/physics)"}</_components.li>{"\n"}<_components.li>{"有的放矢 (yǒu dì fàng shǐ) - \"shoot with a definite target in mind\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"\"shee\""}</_components.strong>{" with a contemplative dip-then-rise — when aiming an "}<_components.strong>{"arrow"}</_components.strong>{", you carefully\nfocus and then release with that thoughtful motion!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"矢 is more commonly used in formal or literary contexts. In everyday speech, 箭 (jiàn) is more\ncommonly used for \"arrow\"."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
