// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 姑 (gū)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" gū"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note: "}<_components.strong>{"\"Ahhhh\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"g"}</_components.strong>{" like "}<_components.strong>{"\"g\""}</_components.strong>{" in \"go\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ū"}</_components.strong>{" sounds like "}<_components.strong>{"\"oo\""}</_components.strong>{" in \"goose\" but held steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"gū"}</_components.strong>{" sounds like "}<_components.strong>{"\"goo\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is "}<_components.strong>{"high and flat"}</_components.strong>{", like holding a steady note:"}</_components.p>{"\n"}<_components.p>{"Say it like you're calling your aunt with respect: "}<_components.strong>{"\"gū\""}</_components.strong>{" — that steady, elevated tone is the\n"}<_components.strong>{"first tone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"姑 (gū) - \"father's sister; aunt\""}</_components.li>{"\n"}<_components.li>{"姑姑 (gū gu) - \"aunt\" (more familiar)"}</_components.li>{"\n"}<_components.li>{"姑娘 (gū niang) - \"girl; young woman\""}</_components.li>{"\n"}<_components.li>{"小姑 (xiǎo gū) - \"father's younger sister\""}</_components.li>{"\n"}<_components.li>{"大姑 (dà gū) - \"father's elder sister\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The first tone's steady high pitch is like respectfully addressing your "}<_components.strong>{"father's sister"}</_components.strong>{" —\nmaintain that elevated, respectful tone throughout!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
