// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 公 (gōng)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" gōng"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"g"}</_components.strong>{" like "}<_components.strong>{"\"g\""}</_components.strong>{" in \"go\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ōng"}</_components.strong>{" sounds like "}<_components.strong>{"\"ohng\""}</_components.strong>{" with a high flat tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"gōng"}</_components.strong>{" sounds like "}<_components.strong>{"\"gohng\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (¯) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're singing a steady, high note: "}<_components.strong>{"\"gōng...\""}</_components.strong>{" — that's the tone pattern of "}<_components.strong>{"gōng"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"公 (gōng) - \"public; duke\""}</_components.li>{"\n"}<_components.li>{"公司 (gōng sī) - \"company\""}</_components.li>{"\n"}<_components.li>{"公园 (gōng yuán) - \"park\""}</_components.li>{"\n"}<_components.li>{"公共 (gōng gòng) - \"public; common\""}</_components.li>{"\n"}<_components.li>{"公开 (gōng kāi) - \"public; open\""}</_components.li>{"\n"}<_components.li>{"公里 (gōng lǐ) - \"kilometer\""}</_components.li>{"\n"}<_components.li>{"办公室 (bàn gōng shì) - \"office\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"公 consistently uses the first tone (gōng) and relates to concepts of \"public,\" \"official,\" or\n\"collective.\" It's commonly used in words related to public services, business, and formal\ninstitutions."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
