// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 欢 (huān)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" huān"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"h"}</_components.strong>{" like "}<_components.strong>{"\"h\""}</_components.strong>{" in \"hat\""}</_components.li>{"\n"}<_components.li><_components.strong>{"uān"}</_components.strong>{" sounds like "}<_components.strong>{"\"wahn\""}</_components.strong>{" held steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"huān"}</_components.strong>{" sounds like "}<_components.strong>{"\"hwahn\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're expressing joy steadily: "}<_components.strong>{"\"huāaaaan\""}</_components.strong>{" — keep it high and level."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"欢迎 (huān yíng) - \"welcome\""}</_components.li>{"\n"}<_components.li>{"欢乐 (huān lè) - \"joy; happiness\""}</_components.li>{"\n"}<_components.li>{"喜欢 (xǐ huan) - \"to like\" (note: becomes neutral tone in compound)"}</_components.li>{"\n"}<_components.li>{"欢庆 (huān qìng) - \"to celebrate\""}</_components.li>{"\n"}<_components.li>{"欢声 (huān shēng) - \"cheerful sounds\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"欢 means \"happy\" — express that joy with a "}<_components.strong>{"high, steady"}</_components.strong>{" tone like sustained laughter: \"huāaan!\""}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
