// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 臼 (jiù)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" jiù"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like stating something firmly"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"j"}</_components.strong>{" like "}<_components.strong>{"\"j\""}</_components.strong>{" in \"jeep\" (soft j sound)"}</_components.li>{"\n"}<_components.li><_components.strong>{"iù"}</_components.strong>{" sounds like "}<_components.strong>{"\"yo\""}</_components.strong>{" in \"yo-yo\", but with fourth tone → sharp drop"}</_components.li>{"\n"}<_components.li><_components.strong>{"jiù"}</_components.strong>{" sounds like "}<_components.strong>{"\"jyo\""}</_components.strong>{" with a definitive falling tone"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" (ˋ) is a "}<_components.strong>{"sharp falling"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it with conviction, like saying "}<_components.strong>{"\"There!\""}</_components.strong>{" when placing something: "}<_components.strong>{"\"jiù!\""}</_components.strong>{" — sharp and\nfinal."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"臼 (jiù) - \"mortar (for grinding)\""}</_components.li>{"\n"}<_components.li>{"石臼 (shí jiù) - \"stone mortar\""}</_components.li>{"\n"}<_components.li>{"臼齿 (jiù chǐ) - \"molar tooth\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Cultural Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"臼 (jiù) refers to a traditional stone or wooden mortar used for grinding grains, spices, or other\nmaterials. It's also used as a radical in Chinese characters and can refer to molar teeth due to\ntheir grinding function."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
