// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 宣 (xuān)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" xuān"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: First tone"}</_components.strong>{" — "}<_components.strong>{"high and flat"}</_components.strong>{" tone, like a steady note"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"x"}</_components.strong>{" like a soft "}<_components.strong>{"\"sh\""}</_components.strong>{" sound, but your tongue is much closer to your teeth"}</_components.li>{"\n"}<_components.li><_components.strong>{"uān"}</_components.strong>{" sounds like "}<_components.strong>{"\"wan\""}</_components.strong>{" but held steady and high"}</_components.li>{"\n"}<_components.li><_components.strong>{"xuān"}</_components.strong>{" sounds like "}<_components.strong>{"\"shwan\""}</_components.strong>{" with a steady high pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"first tone"}</_components.strong>{" (ˉ) is a "}<_components.strong>{"high and flat"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like making an important announcement: "}<_components.strong>{"\"xuān!\""}</_components.strong>{" — that steady, high tone is perfect for\n"}<_components.strong>{"declaring"}</_components.strong>{" something."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"宣 (xuān) - \"to declare; announce; proclaim\""}</_components.li>{"\n"}<_components.li>{"宣布 (xuān bù) - \"to announce; declare\""}</_components.li>{"\n"}<_components.li>{"宣传 (xuān chuán) - \"to publicize; propaganda\""}</_components.li>{"\n"}<_components.li>{"宣言 (xuān yán) - \"declaration; manifesto\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"📍 Usage Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"宣 is often used in formal or official contexts when making public announcements or declarations. It\ncarries a sense of authority and formality."}</_components.p>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p><_components.strong>{"Declare"}</_components.strong>{" — the steady first tone is like the confident voice of someone making an official\n"}<_components.strong>{"announcement"}</_components.strong>{"!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
