// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 学 (xué)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" xué"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Second tone"}</_components.strong>{" — "}<_components.strong>{"rising"}</_components.strong>{" tone, like asking a question: "}<_components.strong>{"\"Really?\""}</_components.strong></_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"x"}</_components.strong>{" like "}<_components.strong>{"\"sh\""}</_components.strong>{" in \"sheep\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ué"}</_components.strong>{" sounds like "}<_components.strong>{"\"weh\""}</_components.strong>{" but with a rising tone"}</_components.li>{"\n"}<_components.li><_components.strong>{"xué"}</_components.strong>{" sounds like "}<_components.strong>{"\"shweh?\""}</_components.strong>{" with a questioning rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"second tone"}</_components.strong>{" (ˊ) is "}<_components.strong>{"rising like a question"}</_components.strong>{":"}</_components.p>{"\n"}<_components.p>{"Start "}<_components.strong>{"low and rise up"}</_components.strong>{" — like enthusiastically asking to learn: "}<_components.strong>{"\"xué?\""}</_components.strong>{" — that's the eager,\nrising second tone."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"学 (xué) - \"to learn; to study\""}</_components.li>{"\n"}<_components.li>{"学习 (xué xí) - \"to study; to learn\""}</_components.li>{"\n"}<_components.li>{"学校 (xué xiào) - \"school\""}</_components.li>{"\n"}<_components.li>{"学生 (xué sheng) - \"student\""}</_components.li>{"\n"}<_components.li>{"大学 (dà xué) - \"university\""}</_components.li>{"\n"}<_components.li>{"中学 (zhōng xué) - \"middle school\""}</_components.li>{"\n"}<_components.li>{"小学 (xiǎo xué) - \"elementary school\""}</_components.li>{"\n"}<_components.li>{"学会 (xué huì) - \"to learn how to; to master\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The second tone's rising pattern is like eagerly asking "}<_components.strong>{"\"Can I learn this?\""}</_components.strong>{" — that enthusiastic\nrise matches the spirit of "}<_components.strong>{"learning"}</_components.strong>{"!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
