// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 豕 (shǐ)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" shǐ"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"sh"}</_components.strong>{" like "}<_components.strong>{"\"sh\""}</_components.strong>{" in \"she\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǐ"}</_components.strong>{" sounds like "}<_components.strong>{"\"ee\""}</_components.strong>{" in \"see\" but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"shǐ"}</_components.strong>{" sounds like "}<_components.strong>{"\"shee\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip (Third tone: ˇ)"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" is "}<_components.strong>{"falling-rising"}</_components.strong>{", like when you're thinking:"}</_components.p>{"\n"}<_components.p>{"Say it like you're contemplating: "}<_components.strong>{"\"shǐ...\""}</_components.strong>{" — that dip-and-rise pattern is the "}<_components.strong>{"third tone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"豕 (shǐ) - \"pig; swine\" (classical/literary term)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Character Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"豕 (shǐ) is primarily used as a "}<_components.strong>{"radical"}</_components.strong>{" in Chinese characters and appears in classical texts. In\nmodern Chinese, 猪 (zhū) is the common word for \"pig.\" However, 豕 appears in various characters\nrelated to pigs or animals:"}</_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"家 (jiā) - \"home; family\" (contains 豕 radical)"}</_components.li>{"\n"}<_components.li>{"豪 (háo) - \"bold; heroic\" (contains 豕 radical)"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🏛️ Historical Context:"}</_components.strong></_components.p>{"\n"}<_components.p>{"豕 (shǐ) is an ancient character that represents the pictograph of a pig. While not commonly used in\neveryday modern Chinese, it's important for understanding character composition and classical texts."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
