// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 显 (xiǎn)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" xiǎn"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"x"}</_components.strong>{" — This is tricky! It's like "}<_components.strong>{"\"sh\""}</_components.strong>{" in \"she\" but "}<_components.strong>{"breathier"}</_components.strong>{" and "}<_components.strong>{"sharper"}</_components.strong></_components.li>{"\n"}<_components.li><_components.strong>{"iǎn"}</_components.strong>{" sounds like "}<_components.strong>{"\"yen\""}</_components.strong>{" but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"xiǎn"}</_components.strong>{" sounds like a breathy "}<_components.strong>{"\"shyen\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎯 Mastering the \"x\" sound:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"x"}</_components.strong>{" in Chinese is "}<_components.strong>{"not"}</_components.strong>{" like English \"x\" (ks). Instead:"}</_components.p>{"\n"}<_components.ol>{"\n"}<_components.li><_components.strong>{"Start with \"sh\""}</_components.strong>{" like in \"she\""}</_components.li>{"\n"}<_components.li><_components.strong>{"Add more breath"}</_components.strong>{" — make it airier and sharper"}</_components.li>{"\n"}<_components.li><_components.strong>{"Keep your tongue tip down"}</_components.strong>{" — don't let it touch the roof of your mouth"}</_components.li>{"\n"}</_components.ol>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"显 (xiǎn) - \"evident; obvious; apparent\""}</_components.li>{"\n"}<_components.li>{"显示 (xiǎn shì) - \"to show; to display\""}</_components.li>{"\n"}<_components.li>{"明显 (míng xiǎn) - \"obvious; evident\""}</_components.li>{"\n"}</_components.ul></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
