// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 氏 (shì)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" shì"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Fourth tone"}</_components.strong>{" — sharp "}<_components.strong>{"falling"}</_components.strong>{" tone, like giving a command"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"sh"}</_components.strong>{" like "}<_components.strong>{"\"sh\""}</_components.strong>{" in \"she\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ì"}</_components.strong>{" sounds like "}<_components.strong>{"\"ee\""}</_components.strong>{" in \"see\" but with the "}<_components.strong>{"fourth tone"}</_components.strong>{" → sharp fall down"}</_components.li>{"\n"}<_components.li><_components.strong>{"shì"}</_components.strong>{" sounds like "}<_components.strong>{"\"she!\""}</_components.strong>{" with a sharp dropping pitch"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip (Fourth tone: ˋ)"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"fourth tone"}</_components.strong>{" is "}<_components.strong>{"sharp and falling"}</_components.strong>{", like making a firm statement:"}</_components.p>{"\n"}<_components.p>{"Say it like you're formally introducing someone's family name: "}<_components.strong>{"\"shì!\""}</_components.strong>{" — that sharp, falling tone\nis the "}<_components.strong>{"fourth tone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"氏 (shì) - \"clan name; surname; family name\""}</_components.li>{"\n"}<_components.li>{"李氏 (Lǐ shì) - \"the Li family\""}</_components.li>{"\n"}<_components.li>{"王氏 (Wáng shì) - \"the Wang family\""}</_components.li>{"\n"}<_components.li>{"姓氏 (xìng shì) - \"surname; family name\""}</_components.li>{"\n"}<_components.li>{"氏族 (shì zú) - \"clan; tribe\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Special Notes:"}</_components.strong></_components.p>{"\n"}<_components.p>{"氏 is a formal way to refer to family names or clans, often used in traditional or formal contexts.\nIn modern Chinese, it's less common in everyday speech but still appears in formal documents,\nhistorical texts, and when referring to distinguished families."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
