// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 苦 (kǔ)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" kǔ"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"k"}</_components.strong>{" like "}<_components.strong>{"\"k\""}</_components.strong>{" in \"key\""}</_components.li>{"\n"}<_components.li><_components.strong>{"ǔ"}</_components.strong>{" sounds like "}<_components.strong>{"\"oo\""}</_components.strong>{" in \"book\", but with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"kǔ"}</_components.strong>{" sounds like "}<_components.strong>{"\"koo\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip (Third tone: ˇ)"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone, like being thoughtful:"}</_components.p>{"\n"}<_components.p>{"Say it like you're contemplating something bitter: "}<_components.strong>{"\"kǔ...\""}</_components.strong>{" — that thoughtful dip-and-rise is the\n"}<_components.strong>{"third tone"}</_components.strong>{"."}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"苦 (kǔ) - \"bitter\""}</_components.li>{"\n"}<_components.li>{"辛苦 (xīn kǔ) - \"hardship, hard work\""}</_components.li>{"\n"}<_components.li>{"痛苦 (tòng kǔ) - \"painful, suffering\""}</_components.li>{"\n"}<_components.li>{"苦瓜 (kǔ guā) - \"bitter gourd\""}</_components.li>{"\n"}<_components.li>{"吃苦 (chī kǔ) - \"to endure hardship\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"苦"}</_components.strong>{" as the contemplative moment when tasting something bitter — that thoughtful reaction\nmatches the "}<_components.strong>{"third tone"}</_components.strong>{"!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📍 Cultural Note:"}</_components.strong></_components.p>{"\n"}<_components.p>{"苦 represents an important concept in Chinese philosophy and medicine, often associated with balance\n(as in bitter foods being healthy) and the value of enduring hardship."}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
