// @ts-nocheck
/*@jsxRuntime automatic*/
/*@jsxImportSource react*/
import {useMDXComponents as _provideComponents} from "@/client/hooks/useMDXComponents";
function _createMdxContent(props: any) {
  const _components = Object.assign(Object.create(_provideComponents()), props.components);
  return <><_components.p><_components.strong>{"🗣️ Pronunciation of 巧 (qiǎo)"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"Pinyin:"}</_components.strong>{" qiǎo"}</_components.li>{"\n"}<_components.li><_components.strong>{"Tone: Third tone"}</_components.strong>{" — "}<_components.strong>{"falling-rising"}</_components.strong>{" tone, like saying \"uh-huh\" when nodding"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🔤 Breakdown:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li><_components.strong>{"q"}</_components.strong>{" like "}<_components.strong>{"\"ch\""}</_components.strong>{" in \"cheap\" but with more aspiration (puff of air)"}</_components.li>{"\n"}<_components.li><_components.strong>{"iǎo"}</_components.strong>{" sounds like "}<_components.strong>{"\"ee-ow\""}</_components.strong>{" with third tone → dip down and rise up"}</_components.li>{"\n"}<_components.li><_components.strong>{"qiǎo"}</_components.strong>{" sounds like "}<_components.strong>{"\"chee-ow\""}</_components.strong>{" with a dip-then-rise"}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"🎧 Tone tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"The "}<_components.strong>{"third tone"}</_components.strong>{" (ˇ) is a "}<_components.strong>{"fall–then-rise"}</_components.strong>{" tone:"}</_components.p>{"\n"}<_components.p>{"Say it like you're discovering something clever: "}<_components.strong>{"\"qiǎo...\""}</_components.strong>{" — that's the thoughtful tone of\nfinding a coincidence!"}</_components.p>{"\n"}<_components.p><_components.strong>{"📝 Common Examples:"}</_components.strong></_components.p>{"\n"}<_components.ul>{"\n"}<_components.li>{"巧 (qiǎo) - \"coincidence; skillful\""}</_components.li>{"\n"}<_components.li>{"巧克力 (qiǎo kè lì) - \"chocolate\""}</_components.li>{"\n"}<_components.li>{"技巧 (jì qiǎo) - \"skill; technique\""}</_components.li>{"\n"}<_components.li>{"巧妙 (qiǎo miào) - \"ingenious; clever\""}</_components.li>{"\n"}<_components.li>{"恰巧 (qià qiǎo) - \"by chance; coincidentally\""}</_components.li>{"\n"}</_components.ul>{"\n"}<_components.p><_components.strong>{"💡 Memory Tip:"}</_components.strong></_components.p>{"\n"}<_components.p>{"Think of "}<_components.strong>{"巧"}</_components.strong>{" as a skillful discovery — that "}<_components.strong>{"third tone"}</_components.strong>{" dip and rise shows the surprise of a\nhappy coincidence!"}</_components.p></>;
}
export default function MDXContent(props: any = {}) {
  const {wrapper: MDXLayout} = {
    ..._provideComponents(),
    ...props.components
  };
  return MDXLayout ? <MDXLayout {...props}><_createMdxContent {...props} /></MDXLayout> : _createMdxContent(props);
}
