name: Clear all GitHub actions caches
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  reset:
    name: Delete all caches
    runs-on: ubuntu-latest

    steps:
      - name: Clear caches
        uses: easimon/wipe-cache@v2
